### ISSUE TITLE
Input Elements behave unexpectedly when using Backspace, Ctrl-Z, Delete 

### ISSUE THREAD

**Issue by apearson** [telerik/kendo-react#327] opened 2019-09-11 19:08 UTC
## Current behavior

Case 1:
When using a normal input component found here [1].  If you type a word, move the cursor to the middle of the world and backspace/delete, the cursor moves to the end of the word.  

Case 2:
Ctrl-Z also behaves unexpectedly or not at all in most cases.  Type a word then backspace a couple letters of the word.  The word does not restore. 

## Expected behavior

Case 1: 
The cursor should stay put and the component should wait til the user is out of focus to make changes to DOM element. 

Case 2: 
Ctrl-Z should act like a normal text field and undo the last action.

## Minimal reproduction of the problem with instructions

KendoUI Document Example: 
https://www.telerik.com/kendo-react-ui/components/inputs/input/

## What is the motivation or use case for changing the behavior?
Input elements should behave like other input elements to not confuse the user. 

## Environment

Package versions:
Reproducible on demo site.

Browser:
- Chrome (desktop) version 76.0.3809.132
- Firefox version 69.0

System:
- TypeScript version: 3.6.2
- Node version: 
    - Node: v10.16.1
    - NPM: 6.9.0
- Platform:  Windows

**Comment by Xizario** [comment] 2019-09-12 07:05
We have some scripts in the site that interfere with the react in the examples iframes. 

Open the example in StackBlitz and it should be working fine. 
https://stackblitz.com/edit/react-mfvuwr?file=app/main.jsx

If you have issue with the component in your project, let us know to investigate further

**Comment by CalvinMills** [comment] 2019-09-18 10:51
I am having this same issue in my application. I have tried to replicate the issue in stackblitz by creating a HOC passing props down to the component which sets the Input component's value to no avail. The only difference in my application is that the application maintains state using redux and passes the state down as props. Is this a known side affect ? If so, are there any previous versions of the kendo-react-inputs package which do not have this issue as we would like to then leverage that particular version in order to overcome this in the short term whilst preparing a long term fix. 

Thanks

**Comment by CalvinMills** [comment] 2019-09-18 11:14
Just an example of how we are using the Input component in our code: 

`             <Input
                name="searchField"
                className="search-field search-input"
                placeholder="Search for anything here"
                onChange={handleChange}
                value={props.searchField}
              />`

The `handleChange` function dispatches a redux action which updates a value in the redux store for the search criteria

The updated value is then passed back down into the component  as props and tied to the value of the input when mapped to props through the `searchField` prop

The HOC I created when trying to replicate the issue leveraged hooks in the HOC to mock my redux store implementation, but this worked without the cursor issue appearing. Hence my question around redux and whether this is a redux specific issue.

**Comment by apearson** [comment] 2019-09-18 20:36
@CalvinMills Check if your component is rendering after each key press.  This caused my input box's behavior to act strangely.

**Comment by CalvinMills** [comment] 2019-09-19 09:03
Hi @apearson, thank you for replying. My component is definitely re rendering on every key press since the value is updated and the component delta forces a re render. 

However, I created this stackblitz https://react-mfvuwr-gwhbnp.stackblitz.io, where the Input component is also re rendering on every key press, from hooks and not redux mind, but the render cycle should mimic my environment. And in the case of the stackblitz, the issue is not present, but in my case it is. Any thoughts ?

**Comment by Xizario** [comment] 2019-09-19 10:16
I will reopen this, as the conversation continues. Few problems that can lead to this behaviour:

* Component unmounts and mounts instead of re-rendering. Can happen if key of some of the parents is changed, and/or they are in array without keys.
* there is something in the site that is listening on keydown/keyup and do something outside the react lifecycle
* multiple setState-s are called in one of the parent components with different parameters, and react batch them, before calling the internal setState of the Input component.
* Setting the value, from the event happens in async way. Check if you don't have any timeouts in your reducers.

**Comment by CalvinMills** [comment] 2019-09-19 11:02
Hi @Xizario, thanks for getting in touch, below are my responses to each of the points you've raised:

- Setting the value, from the event happens in async way. Check if you don't have any timeouts in your reducers. (This is definitely not happening, simple redux action which updates the state with an object payload)
- there is something in the site that is listening on keydown/keyup and do something outside the react lifecycle. (There are no components in my app listening on keyup/keydown)
- multiple setState-s are called in one of the parent components with different parameters, and react batch them, before calling the internal setState of the Input component. (I dont use any class components in my app).
- Component unmounts and mounts instead of re-rendering. Can happen if key of some of the parents is changed, and/or they are in array without keys. (No direct parents change on change of the input box - or the state change that follows, not sure what the best way to detect if the component is being mounted instead of re rendered ? It isnt in an array of components btw)

Hope this helps! 

Happy to send a thinned down version of my environment if needs be, may take me a while though!

**Comment by CalvinMills** [comment] 2019-09-20 08:24
Just an update here. I have found the culprit.

If you are rendering the `Input` component from a parent which uses composition, i.e. renders the component with the `Input` component in it using the `{props.children}` approach, this is where the issue occurs.

I can change this in my code but requires a big change and considering composition is preferred over inheritance in the react ecosystem it seems like something that should be fixed potentially ? 

@Xizario, thoughts ?

**Comment by Xizario** [comment] 2019-09-20 08:42
I think we can simplify the code of the `Input`, and it will start working like normal `input` in both controlled and uncontrolled modes by removing its internal state and chancing some of the logic to make the component pure. 

Could you confirm your code works without selection/cursor problems when you are using normal `<input>` element instead of the KendoReact `Input`?

**Comment by CalvinMills** [comment] 2019-09-20 08:44
Yes, the issue does not occur when using a normal html `input` tag. 

I have resolved the issue in my code for the time being by removing some unnecessary composition, but I can imagine that myself as well as other people will no doubt run into this issue at some point in the future.

**Comment by tomeczekstecc** [comment] 2021-03-23 20:36
> Yes, the issue does not occur when using a normal html `input` tag.
> 
> I have resolved the issue in my code for the time being by removing some unnecessary composition, but I can imagine that myself as well as other people will no doubt run into this issue at some point in the future.

You are right. I ran into the  same problem and can't switch to normal ```input``` tag since I use **react semantic-ui**

**Comment by kdikov82** [comment] 2023-01-24 22:03
Closed due to the lack of example reproducing the issue

**Closed by kdikov82** 2023-01-24 22:03 UTC
Labels: pkg:inputs, documentation, needs more information, FP: Unplanned
