### ISSUE TITLE
ColumnMenu dropdown is not closed on secondary click on trigger

### ISSUE THREAD

**Issue by yakunins** [telerik/kendo-react#1073] opened 2021-09-08 15:54 UTC
## Bug report
ColumnMenu dropdown is not closed (reopened) on secondary click → https://www.telerik.com/kendo-react-ui/components/grid/columns/column-menu/

## Current behavior
Second click on menu trigger must close the dropdown. It actually does it on `mouseDown`, but consecutive `mouseUp` event reopens the menu. In case of touch devices second touch closes the dropdown, good news here!

## Expected behavior
Second click on menu trigger must close the dropdown.

![image](https://user-images.githubusercontent.com/2505676/132541320-0fa025fc-d229-47ba-87bc-6d9d68abd8d3.png)

## Minimal reproduction of the problem with instructions
1. Go to https://www.telerik.com/kendo-react-ui/components/grid/columns/column-menu/
2. Click on any columnMenu (three vertical dots) in a grid
3. Click again
4. Menu dropdown reopened (unexpected, need to be closed)

## What is the motivation or use case for changing the behavior?
Expected behavior for menu is preferable.

Browser:
- Chrome (desktop) version 93.0.4577.63 (Official Build) (64-bit)

System:
- Platform: Windows 10 (64-bit)

**Comment by simonssspirit** [comment] 2021-09-28 08:58
this is a duplicate of https://github.com/telerik/kendo-react/issues/1028

**Closed by simonssspirit** 2021-09-28 08:58 UTC
