### ISSUE TITLE
Grid columns cannot be reordered inside shadowRoot 

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1470] opened 2023-01-13 14:02 UTC
Currently, it is not possible to reorder columns when the Grid is rendered inside a ShadowRoot, because the click on the header is ignored.

This can be reproduced in the following example:

https://stackblitz.com/edit/react-dropdownbutton-example-qwsij1?file=app/main.jsx

Ticket ID: 1593434

**Comment by nstoychev** [comment] 2023-01-27 11:10
Fixed in 5.11.0-dev.202301271039.

Example: https://stackblitz.com/edit/react-dropdownbutton-example-3huawj?file=app%2Fmain.jsx

**Comment by veej** [comment] 2023-02-13 10:54
Hi @nstoychev. We upgraded Kendo's dependencies to v5.11.0, but the issue doesn't seem to be solved for us.
Debugging the new code, looks like you implemented a logic based on click event's coordinates, but it seems to be completely wrong.

Even in your example, it's enough to add a marginTop to your table, and it's again impossible to drag&drop columns:
https://stackblitz.com/edit/react-dropdownbutton-example-gq2jfk?file=app%2Fmain.jsx

**Comment by nstoychev** [comment] 2023-02-13 11:55
> Hi @nstoychev. We upgraded Kendo's dependencies to v5.11.0, but the issue doesn't seem to be solved for us. Debugging the new code, looks like you implemented a logic based on click event's coordinates, but it seems to be completely wrong.
> 
> Even in your example, it's enough to add a marginTop to your table, and it's again impossible to drag&drop columns: https://stackblitz.com/edit/react-dropdownbutton-example-gq2jfk?file=app%2Fmain.jsx

Hi @veej, I'll take care and probably will refactor it. I am not sure why we use the coordinates since we can get the DOM element from the event.target. Thanks for checking this.

**Comment by nstoychev** [comment] 2023-02-14 12:10
Hi @veej,

Actually, we cannot use the event.target here because it points to the app element.

Can you test the following change on your side:
At "@progress/kendo-react-data-tools" package, file - /header/utils/index.ts replace the following:
const pos = { top: c.offsetTop, left: c.offsetLeft, height: c.offsetHeight, width: c.offsetWidth };
to be
const pos = c.getBoundingClientRect();

Please, let me know if this change works for you.

If it doesn't, provide me an example, so I can check it.

Since you mentioned that this is completely wrong, I wonder do you have better idea.

**Comment by nstoychev** [comment] 2023-02-20 08:10
Hi @veej.

We published v5.11.1-dev.202302171846 with this change. Let me know if you still experience the issue.

**Comment by veej** [comment] 2023-02-20 14:57
Hi @nstoychev. Just tested the new dev version in our app and I can confirm the drag&drop now works flawlessly in our use case. Thank you very much for your support! 🙏

**Closed** 2023-02-26 21:41 UTC
Labels: bug, pkg:grid
