### ISSUE TITLE
Font size is not changing

### ISSUE THREAD

**Issue by VladMishyn01** [telerik/kendo-react#997] opened 2021-07-08 14:12 UTC
Hi , there. 

Recently i tried to use Kendo for React to create PDF document.  

But i faced with one issue, i cannot change font size of text. 

No matter what properties i use, and what tags i am using it's always same size, even for `<h1>`

The wierdest thing that everything else working fine colors, margin, font colors, etc.

**Comment by TrinityMunro** [comment] 2021-07-08 20:17
I got the same problem

**Comment by k-koehler** [comment] 2021-07-12 19:31
same here

**Comment by nstoychev** [comment] 2021-07-14 08:14
@VladMishyn01
Can you provide an example where we can see the issue? I tried it here and it works as expected - https://stackblitz.com/edit/react-ybg8it?file=app/main.jsx.

**Comment by prabha024** [comment] 2021-12-01 07:31
i got the same problem. have you fixed it?

**Comment by VladMishyn01** [comment] 2021-12-01 08:57
> i got the same problem. have you fixed it?
Unfortunately i didn't found any working solutions.
I switched to JsPdf

**Comment by simonssspirit** [comment] 2022-01-04 08:16
Could please anyone share an example so we can observe the issue and potentially fix it.

If an example with the issue is not provided we will proceed with closing the item.

**Closed** 2023-01-30 20:47 UTC
Labels: pkg:pdf-export
