### ISSUE TITLE
Title attribute causes tooltip to appear in the Drawer component

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1145] opened 2021-11-24 16:14 UTC
When hovering over an item in the Drawer component, а tooltip appears. It is caused by the `title` attribute in the `ul` element. 
Replacing the `title` attribute with the `aria-label` instead will solve the tooltip issue but still do not cause an accessibility issue.

TicketID: 1543700

**Comment by silviyaboteva** [comment] 2021-12-03 13:15
Duplicate of https://github.com/telerik/kendo-react/issues/1080

**Closed by silviyaboteva** 2021-12-03 13:15 UTC
Labels: bug, pkg:layout
