### ISSUE TITLE
Virtual Scrolling issue when data is filtered to less than page size

### ISSUE THREAD

**Issue by jhursey** [telerik/kendo-react#174] opened 2019-01-24 20:37 UTC
## I'm submitting a...

* Bug report 

## Current behavior

Given a react kendo grid configured such that
* the sum of the column widths is greater than the table width, i.e. the horizontal scroll bar is visible
* scroll mode is set to 'virtual'
and the data provided to the grid is only enough to fill up a little over half the page
when the grid is rendered
then the vertical scroll bar shows as available
and results in unpredictable behavior.

## Expected behavior
Match the behavior of the grid if the table is wider than the sum of the column widths.

## Minimal reproduction of the problem with instructions
https://react-n4yebv.stackblitz.io

## Environment
Reproducible in your production demos. 

Browser:

- Chrome (desktop) version XX
- Edge version XX

**Comment by simonssspirit** [comment] 2019-01-25 10:59
@jhursey Thank you for the details.

Having items at least equal to the number of visible items on the page is one of the requirements of the virtual scrolling:

"(Required) pageSize—To avoid unexpected behavior during scrolling, set pageSize to at least the number of visible Grid elements. The number of the visible Grid elements is determined by the height and rowHeight settings of the Grid."

https://www.telerik.com/kendo-react-ui/components/grid/scroll-modes/#toc-virtual-scrolling

**Comment by kdikov82** [comment] 2022-07-22 15:02
The virtual scrolling can be disabled conditionally if the number of records is less than the required pageSize.

**Comment by kdikov82** [comment] 2022-07-22 15:02
Closing due to possible workaround

**Closed by kdikov82** 2022-07-22 15:02 UTC
Labels: pkg:grid
