### ISSUE TITLE
BUG; @progress/kendo-react-grid, Grid, expandField interupts onItemChange

### ISSUE THREAD

**Issue by smsdodwyer** [telerik/kendo-react#333] opened 2019-09-19 09:30 UTC
# Bug report

## Current behavior
Calling `onChange` to update the same field used in `expandField` does not call `onItemChange`.

## Expected behavior
`onItemChange` gets called, similar to how `onItemChange` still gets called if updating the field used in `editField`

## Minimal reproduction of the problem with instructions
NOTE: uses `console.log` for demo purposes
https://stackblitz.com/edit/react-mkzxgv?file=app/main.jsx

## What is the motivation or use case for changing the behavior?
Cannot update `expandField` without workarounds.
This is difficult when `editField` === `expandField`

**Comment by Xizario** [comment] 2019-09-19 10:29
If **expandField** is defined, the **onExpandChange** will be called instead of **onItemChange** when this field changes. It is by design.

Do you use **onExpandChange** event? If you don't have expand/collapse functionality with details, you can remove the usage of expandField.

If I understand correctly, this bug report is actually a request for removing the **onExpandChange** and firing **onItemChange** at any case. As it is generally acceptable, I think it will be breaking change, so I will keep it here for further discussion probably in next major version

**Comment by kdikov82** [comment] 2022-07-31 08:33
At this point this will be a huge breaking change over existing projects, so I am closing the request.

**Closed by kdikov82** 2022-07-31 08:33 UTC
Labels: discussion
