### ISSUE TITLE
Unable to conditionally render content inside a PanelBar. Exception is thrown on PanelBar expand/collapse

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#317] opened 2019-08-28 11:23 UTC
## I'm submitting a...

* Bug report 

## Current behavior
If you conditionally render an element inside a PanelBar using && syntax, when you try to expand/collapse the PanelBar it throws a Javascript exception: cannot read props of null

This is similar to an issue that was fixed here: https://github.com/telerik/kendo-react/issues/152

There is a workaround that can be used temporarily as suggested in above TabStrip issue before that got fixed

## Expected behavior
Do not throw exception. Expand/Collapse should still work

## Minimal reproduction of the problem with instructions
See fork of demo
https://stackblitz.com/edit/react-x9bhrh?file=app/main.jsx

Click the panelbar heading to collapse panelbar

## What is the motivation or use case for changing the behavior?
Ability to use valid jsx syntax and not crash component

## Environment

Package versions:
 "react": "16.9.0",
    "react-dom": "16.9.0",
    "@progress/kendo-react-layout": "3.2.2",
    "@progress/kendo-react-intl": "3.2.2",
    "@progress/kendo-react-dropdowns": "3.2.2",
    "react-router-dom": "5.0.1",
    "prop-types": "15.7.2",
    "react-transition-group": "4.2.2"

```

Browser:
- Chrome (desktop) version 76

**Comment by kspeyanski** [comment] 2019-10-09 06:11
Hello @k290 ,

The issue has been fixed in our `dev` channel, and will be released with version `3.5.0` of the `@progress/kendo-react-layout` package.

I've updated the provided stackblitz example to use `@progress/kendo-react-layout@dev` and the issue is no longer reproducible:

https://stackblitz.com/edit/react-x9bhrh-tc1jcx?file=app/main.jsx

Thank you for reporting it!

**Closed by kspeyanski** 2019-10-09 06:11 UTC
Labels: bug, pkg:layout
