### ISSUE TITLE
Portals are not currently supported error appears when setting MultiSelect opened property inside Popup

### ISSUE THREAD

**Issue by shaibam** [telerik/kendo-react#192] opened 2019-02-18 14:22 UTC
## I'm submitting a bug

* Bug report 

## Current behavior
When rendering a Popup component which contains a child MutiSelect component with the opened prop set to true, the page crashes. displaying : Error in /turbo_modules/react-dom@16.8.2/cjs/react-dom-server.browser.development.js (53:15)
Portals are not currently supported by the server renderer. Render them conditionally so that they only appear on the client render.

## Expected behavior
MutiSelect component  should be open, and data should be displayed

## Minimal reproduction of the problem with instructions
When rendering a Popup component which contains a child MutiSelect component with the opened prop set to true, the page crashes. displaying : Error in /turbo_modules/react-dom@16.8.2/cjs/react-dom-server.browser.development.js (53:15)
Portals are not currently supported by the server renderer. Render them conditionally so that they only appear on the client render.

https://stackblitz.com/edit/react-wmc75u?file=app%2Fmain.js
-->

## What is the motivation or use case for changing the behavior?
auto open multiSelect whn opening popup
## Environment

Package versions:

```
+-- @progress/kendo-data-query@1.5.0
+-- @progress/kendo-drawing@1.5.8
+-- @progress/kendo-file-saver@1.0.7
+-- @progress/kendo-react-buttons@2.6.1
+-- @progress/kendo-react-charts@2.6.1
+-- @progress/kendo-react-dateinputs@2.5.0
+-- @progress/kendo-react-dropdowns@2.5.0
+-- @progress/kendo-react-excel-export@2.6.1
+-- @progress/kendo-react-grid@2.5.0
+-- @progress/kendo-react-inputs@2.5.0
+-- @progress/kendo-react-intl@2.5.0
+-- @progress/kendo-react-layout@2.5.0
+-- @progress/kendo-theme-bootstrap@2.17.1
+-- @progress/kendo-theme-default@2.62.0
+-- @progress/kendo-theme-material@1.5.2
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

Example : https://stackblitz.com/edit/react-wmc75u?file=app%2Fmain.js

![kendo-popup-multiselect](https://user-images.githubusercontent.com/1324331/52957012-5fb1a000-3399-11e9-8b56-68a1d89da0ab.PNG)
![kendo-popup-multiselect-bug](https://user-images.githubusercontent.com/1324331/52957014-604a3680-3399-11e9-98d9-f8da5ce4b9a4.PNG)

**Comment by kelseygasser** [comment] 2019-04-16 15:58
Did you ever discover the solution to this issue? I am getting a similar error, but it seems for different reasons

**Comment by nstoychev** [comment] 2019-05-07 11:27
@shaibam, @kelseygasser 
The problem is that current Popup implementation uses [ReactDOMServer.renderToStaticMarkup](https://reactjs.org/docs/react-dom-server.html#rendertostaticmarkup)
function to prerender the popup content and calulate its size and position. Along with that, the popup also uses [ReactDOM.createPortal](https://reactjs.org/docs/portals.html). The error raises when ReactDOMServer.**renderToStaticMarkup** renders an element which has been rendered by ReactDOM.**createPortal**. In our case, nested popups.

For now, I can suggest to avoid rendering of nested opened popups. Here is how the above example can be changed to prevent the error: https://stackblitz.com/edit/react-wmc75u-njysql?file=app/main.js

**Comment by SimchaCahn** [comment] 2020-04-14 14:50
@nstoychev I'm having the same issue when using a daterange calendar in a popup component. What can I do to get that working?

**Comment by steve-cahn** [comment] 2020-04-14 19:53
@nstoychev I'm having the same issue when using a daterange calendar in a popup component. What can I do to get that working?

**Comment by nstoychev** [comment] 2020-06-12 09:17
Resolved in dev channel. The Popup does not use ReactDOMServer anymore - https://stackblitz.com/edit/react-wmc75u-bucfal?file=app/main.js.

**Closed** 2020-06-12 09:17 UTC
Labels: pkg:popup
