### ISSUE TITLE
Grid -> Columns -> Change Column Width from outside does not rerender the table with the new column width

### ISSUE THREAD

**Issue by andreastoermer** [telerik/kendo-react#12] opened 2018-03-21 07:45 UTC
## I'm submitting a...

* Bug report 

## Current behavior

  * The necessary data for the columns are part of an object inside the state of the component that use the kendo react grid
  * Update the Width Property of the Column does not trigger a rerender of the table
  * Make a resize of a column trigger the rerender of this column with the new width

## Expected behavior
  * After updating the width of a column, rerender the column with this new width
  * with version 0.3 it works

## What is the motivation or use case for changing the behavior?
We used the kendo react solution for tables with many columns and not much space for the filter row. so we decided to add a minimal width to the table columns, when filter row is activated. We have build a toggle Button to activate/deactivate the filter row and with this button we also want to change the minimal width of the columns.

## Environment

Package versions:

```
@progress/kendo-react-grid@0.4.0
```

Browser:

- Firefox version 52.1

System:
- TypeScript version: 2.3
- Node version: 6.11.1
- Platform:  Windows

**Comment by andreastoermer** [comment] 2018-03-22 12:52
After testing it again with the 0.3.0 version (there it works), i've changed this issue to a bug report

**Comment by andreastoermer** [comment] 2018-04-03 05:52
@mitagg @Xizario Any new updates about this problem?

**Comment by Xizario** [comment] 2018-04-03 06:21
@andreastoermer, the issue is caused by the introduction of the [column resizing](https://www.telerik.com/kendo-react-ui/components/grid/columns/resizing/) functionality. If the widths from the definition of the columns are always controlling the actual widths, then the resizing will not be possible.

We are planing to add `DefaultWidth` property for the initial values that works nice with the resizing. And the `Width` prop will work as in the previous version, thus fixing this issue.

**Comment by andreastoermer** [comment] 2018-04-03 06:52
@Xizario Thanks for your reply. Any ETA for the solution?

**Comment by Xizario** [comment] 2018-04-04 14:58
@andreastoermer in `@progress/kendo-react-grid@0.5.0-dev.201804041130` you should be able to control the widths, and changing them will cause re-renders in case the [resizable](https://www.telerik.com/kendo-react-ui/components/grid/api/GridProps/#toc-resizable) is `false`.

**Comment by Xizario** [comment] 2018-04-06 05:48
Fixed in `0.5.0`

**Closed by Xizario** 2018-04-06 05:48 UTC
Labels: bug, pkg:grid
