### ISSUE TITLE
Value axes should stretch to fill the entire pane

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#929] opened 2021-05-17 09:56 UTC
Value axes should stretch to fill the entire pane.

In many cases, the panes are used to cover the case of Charts being aligned horizontally/vertically with other Charts.

We can also introduce an option to align different Charts as this will resolve the panes-related issues.

Related to https://github.com/telerik/kendo-charts/issues/231

**Comment by PekoPPT** [comment] 2024-07-24 15:02
The issue is fixed with the January 2024 release. Here is a working example - https://stackblitz.com/edit/react-dpqnje-5xaege?file=app%2Fmain.jsx

**Closed by PekoPPT** 2024-07-24 15:02 UTC
Labels: Bug, pkg:Charts, SEV: Low
