### ISSUE TITLE
Scheduler overlaps events when the order prop is enabled in WeekView

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1533] opened 2023-03-31 12:34 UTC
When using the order prop for a custom SchedulerViewItem in the WeekView, the events are garbled and overlapping. 

This can be seen in the following example:

https://stackblitz.com/edit/react-qfmkkp-7r7nxr?file=app/main.jsx

Ticket ID: 1595713

**Comment by kspeyanski** [comment] 2024-11-08 09:48
In the provided demo the `props.dataItem.order` is `undefined`, thus all events are stacked since there is no hierarchy present.

Closing until more info or reproducible

**Closed by kspeyanski** 2024-11-08 09:48 UTC
Labels: Bug, pkg:Scheduler, SEV: Medium
