### ISSUE TITLE
[SplitButton] SplitButtonProps export from @progress/kendo-react-buttons

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1653] opened 2023-07-28 11:53 UTC
SplitButtonProps is currently exported from `@progress/kendo-react-buttons/dist/npm/ListButton/models/ListButtonProps`.
However, it should be exported from `@progress/kendo-react-buttons` directly.

Ticket ID: 1617910

**Comment by zdravkov** [comment] 2024-02-14 06:55
The issue is fixed in the dev channel on KendoReact @progress/kendo-react-buttons package.

**Closed by zdravkov** 2024-02-14 06:55 UTC
Labels: Enhancement, pkg:Buttons
