### ISSUE TITLE
KendoGrid - toggle column rendering slow performance

### ISSUE THREAD

**Issue by araasryan** [telerik/kendo-react#1137] opened 2021-11-12 14:55 UTC
## I'm submitting a...

* Bug report 
## Current behavior

When dynamically changing rendering columns whole the Grid is being re-rendered

## Expected behavior

The best case would be to only render newly added Column

## Minimal reproduction of the problem with instructions

Here is a sample that will demonstrate the issue. You should check with React Profiler
https://stackblitz.com/edit/react-4b7p7z?file=app/main.tsx

<img width="1792" alt="Screen Shot 2021-11-12 at 6 47 16 PM" src="https://user-images.githubusercontent.com/58461276/141485556-835ac4d3-ce04-4e52-aba6-adeb75cffaa3.png">

## What is the motivation or use case for changing the behavior?

When working on real data with custom editable cells and lots of data this small feature is freezing the whole UI for a few seconds as the whole Grid is being rendered. I believe this is enough motivation.

**Comment by vladimirivanoviliev** [comment] 2022-02-10 15:55
We are constantly test and evaluate the Grid performance and found that actual cells are not using correct React key which might impact performance. The issue is now fixed on our side and it will be shipped with next dev versions.

In order to utilize the new optimisations you need to set the following props:
- `dataItemKey` prop of the Grid - responsible for row keys, must be unique per record
- `id` prop of the columns - responsible for cell keys. Need to be unique per column

**Closed** 2022-03-11 14:50 UTC
Labels: pkg:grid
