### ISSUE TITLE
Resizing a locked column causes misalignment.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#413] opened 2019-12-06 09:26 UTC
Resizing a locked column causes misalignment.

This can be observed on the following demo by resizing the name column to make it smaller:

https://stackblitz.com/edit/react-kgjunf-zgfp6y?file=app/main.jsx

**Comment by Xizario** [comment] 2020-10-14 10:03
Currently the issue can be bypassed by controlling the column width:
https://stackblitz.com/edit/react-kgjunf-govk9f
It comes with some performance penalty, as it requires all non-frozen cells to be rerendered.
In the future fix we are looking for setting the left of each cell using css var and avoid rerenders.

**Comment by simonssspirit** [comment] 2021-03-30 12:20
reported again in 1513152, raising priority.

**Comment by vladimirivanoviliev** [comment] 2021-03-31 07:10
Gantt / TreeList affected too.

**Comment by kkapitanova** [comment] 2021-04-08 07:17
reported again in 1514389

**Comment by S1r-Lanzelot** [comment] 2021-04-08 19:02
+1

**Comment by kkapitanova** [comment] 2021-04-13 12:17
reported again in 1515184

**Comment by S1r-Lanzelot** [comment] 2021-04-30 14:51
Any update on this issue? Is it being considered for a future release? Thank you.

**Comment by kkapitanova** [comment] 2021-06-18 10:15
Reported again in 1524472

**Comment by kdikov82** [comment] 2021-12-20 05:05
Reported again for the TreeList in Ticket ID: 1546419

**Comment by wiznotwiz** [comment] 2022-06-17 19:35
Any updates here?

**Comment by kdikov82** [comment] 2023-01-26 11:32
Still reproducible with the latest versoin:
[https://stackblitz.com/edit/react-n1jnig?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-n1jnig?file=app%2Fmain.jsx)

**Comment by iadnonov** [comment] 2023-02-06 09:43
Reported again in ticket: 1594875

**Comment by vveesseelliinnaa** [comment] 2023-02-27 13:08
Reported again in Ticket ID: 1598847

**Comment by vveesseelliinnaa** [comment] 2023-06-13 07:12
Reported again in Ticket ID: 1612154

**Comment by wiznotwiz** [comment] 2023-06-13 12:44
Any ideas on when this might increase in priority and/or get done? We use TreeList all over the place now, but contending with column widths is always a pain because of this bug. The columns just don't behave as well as they do in KendoReact Grid.

**Comment by zdravkov** [comment] 2023-06-13 12:56
Hey @wiznotwiz ,
Thank you for your feedback, the priority of the issue is increased and it is in our to do list now, we will do our best to include it in some of the next patch releases yet at the moment can't commit on exact ETA.
Greatings,
Plamen

**Comment by zdravkov** [comment] 2023-09-05 11:47
The issue for the DataGrid is fixed in version 5.17.0. We have created a separate issue to update the behavior of the TreeList to behave as the DataGrid and we will handle it as another issue - [here](https://github.com/telerik/kendo-react/issues/1694) .

**Closed by zdravkov** 2023-09-05 11:47 UTC
Labels: bug, pkg:grid, Priority 4, SEV: Medium
