### ISSUE TITLE
KendoReact Scheduler MonthView shows wrong number of days, probably because of DST

### ISSUE THREAD

**Issue by stuartwmurray** [telerik/kendo-react#529] opened 2020-03-25 09:21 UTC
## I'm submitting a...
* Bug report 

## Current behavior
![image](https://user-images.githubusercontent.com/11416577/77520612-91b6ff00-6ed5-11ea-916a-9e99b503fd5b.png)

Note first row, there is a Sunday the 5th of April on both the first and second row. There is also 2x Sunday headings.

## Minimal reproduction of the problem with instructions
1. Open demo: https://www.telerik.com/kendo-react-ui/components/scheduler/views/month/
2. Select April 2020

I believe it is completely a daylight savings / maths issue. I am in Melbourne Australia which switches from +10 to +11.

## What is the motivation or use case for changing the behavior?
Its broken for anyone in DST

## Environment
Browser:
- Firefox version 74

The problem is in function toSlots in slotsService.ts

Line 26:
```
                offset = (zonedEnd.timezoneOffset - zonedStart.timezoneOffset) * MS_PER_MINUTE;

                const start = new Date(zonedStart.getTime() + offset);
                const end = new Date(zonedEnd.getTime() + offset);
```

This doesn't seem to account for DST correctly (guess) - Certainly the logic is super weird.

I have worked around it by converting everything carefully into UTC which has no DST - however this is not ideal and will make some features not work correctly I'm sure.

**Comment by kspeyanski** [comment] 2020-03-25 09:30
Hello @stuartwmurray ,

Thank you for reporting this. I can confirm that the issue is with DST. 
We have already implemented a fix, which is in QA phase, and we will be publishing it with the upcoming `dev` versions of the `@progress/kendo-react-scheduler`. 

I'll keep this issue updated once the fix has been published.

**Comment by stuartwmurray** [comment] 2020-03-25 10:24
Hi,

Thanks for that. My workaround proved to have its own problems. Is there any way I can get access to your fix?

I have a progress/telerik account if there is an easy way to move the conversation over there?

**Comment by kspeyanski** [comment] 2020-03-25 10:57
Currently the fix is still on Pull Request and it not yet available.

Due to the complexity of the DST calculations, we want to make sure we test all the possible scenarios before releasing the fix.

While i cannot give an exact date, we are expecting to release it next week, given the testing goes as expected.

**Comment by kspeyanski** [comment] 2020-04-06 12:22
Hello @stuartwmurray ,

We have published the fix with the latest `dev` version of the `@progress/kendo-react-scheduler` package. You can observe the fix in action in the following stackblitz example:
https://stackblitz.com/edit/react-iqg9se?file=package.json

For more information about obtaining development builds, please refer to this article:
https://www.telerik.com/kendo-react-ui/components/installation/development-builds/

Please be advised that all scheduler dependencies should also be updated to the latest `dev` version.

**Closed by kspeyanski** 2020-04-06 12:22 UTC
Labels: bug, pkg: scheduler
