### ISSUE TITLE
All popups flicker on their closing animation when using ReactDOM.createRoot (React 18's new rendering engine)

### ISSUE THREAD

**Issue by revov** [telerik/kendo-react#1297] opened 2022-05-10 09:35 UTC
## I'm submitting a...
* Bug report 

## Current behavior
When closing a popup (on any control that uses Popup or the Popup directly) the animation flickers (just before the height of the popup reaches zero it flickers to full height for a brief moment).

## Expected behavior
Popup closing animation should not flicker.

## Minimal reproduction of the problem with instructions
This is a fork of the basic Popup example, just using `ReactDOM.createRoot` for mounting instead of `ReactDOM.render`. If we use `ReactDOM.render` even with React 18 it works as expected:
https://stackblitz.com/edit/react-y87uu6?file=app%2Fmain.tsx
https://react-y87uu6.stackblitz.io/

## Environment
@progress/kendo-react-popup: 5.2.0
react: 18.1.0

**Comment by Tommuh** [comment] 2022-05-21 21:12
Dropdowns as well.

**Comment by lorena-caia** [comment] 2022-06-02 13:13
This issue is reproducible using the "@progress/kendo-react-popup": "5.3.0" version as well

**Comment by nstoychev** [comment] 2022-06-06 10:21
Fixed in our development channel version 5.4.0-dev.202206061009.
Example - https://stackblitz.com/edit/react-y87uu6-uurpwt?file=app%2Fmain.tsx.

**Comment by lorena-caia** [comment] 2022-06-07 05:20
> Fixed in our development channel version 5.4.0-dev.202206061009. Example - https://stackblitz.com/edit/react-y87uu6-uurpwt?file=app%2Fmain.tsx.

Thank you! Indeed in the 5.4.0-dev.202206061009 version, the issue is no longer reproducible 🥳

**Closed** 2022-06-28 13:05 UTC
Labels: bug, pkg:popup
