### ISSUE TITLE
[DropDownButton] The tabindex is not removed if the popup is closed after clicking outside of it

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1668] opened 2023-08-14 06:44 UTC
The tabindex="-1" is added to the wrapping element of the DropDownButton when the popup is opened, but when the popup is closed after clicking outside of it will keep the tabindex:

- https://stackblitz.com/edit/react-sex7yz?file=app%2Fmain.jsx

Expected behavior:
The tabindex property should be removed regardless of how the popup is closed

**Comment by zdravkov** [comment] 2024-02-14 06:57
The issue is fixed in the dev channel on KendoReact @progress/kendo-react-buttons package. https://stackblitz.com/edit/react-sex7yz-tw1suw

**Closed by zdravkov** 2024-02-14 06:57 UTC
Labels: Bug, pkg:Buttons, SEV: Medium
