### ISSUE TITLE
Remove focus style from the TimePicker input after the Cancel button is clicked.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1144] opened 2021-11-24 07:28 UTC
Remove focus style from the TimePicker input after the Cancel button is clicked.

https://www.telerik.com/kendo-react-ui/components/dateinputs/timepicker/

Open the picker.

Click the Cancel button.

Notice how the focus styles are still visible.

Similar to https://github.com/telerik/kendo-react/issues/1022

Please ensure that all Date inputs do not have the same issue like the DatePicker, the DateRangePicker, etc.

**Comment by kspeyanski** [comment] 2022-01-26 06:54
We've done a major refactor of our `focus` styles in version `5.0.0` of all KendoReact components and the `kendo-themes` packages.

The issue is no longer observable in the TimePicker demo, so I will be closing this issue for now.

For the full list of changes in `v5` please refer to the changelog:
https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#cbaeb3eb-8e8c-593d-b489-4d8c3bdfee58

**Closed by kspeyanski** 2022-01-26 06:54 UTC
Labels: bug, pkg:dateinputs
