### ISSUE TITLE
KendoReact Editor  is changing the dots to ''&" i.e ( .....................   ==> &&&&&&&&&)  major issue 

### ISSUE THREAD

**Issue by Genesis671230** [telerik/kendo-react#2454] opened 2024-08-09 06:45 UTC
### I'm submitting a...

- [ ]  Bug report

> Current behavior:

When exporting content from the KendoReact Editor as a PDF, all dot characters (.) in the text are replaced with ampersand characters (&). For example, a string of dots (.....................) is converted to a string of ampersands (&&&&&&&&&). This issue significantly alters the content in the exported PDF, making it unusable.

> Expected behavior:

The dots (.) in the text should remain unchanged when exporting the content as a PDF. The PDF output should match the input text exactly, without replacing any characters.

> Minimal reproduction of the problem with instructions:

              1. Create a KendoReact Editor instance.
              2. Enter a series of dots (.....................) in the editor.
              3. Export the content as a PDF using the available export functionality.
              4. Observe that the dots in the exported PDF are replaced with ampersands (&&&&&&&&&).
              5. What is the motivation or use case for changing the behavior?

This issue impacts the accuracy of documents generated from the KendoReact Editor. Users rely on the editor to produce precise PDF exports, and this bug disrupts that expectation, leading to potential miscommunications or errors in documents.

> Environment:

Package versions:

**@progress/kendo-react-editor:  "^8.0.0"**

> Browser:

**Chrome (web) Version 127.0.6533.90 (Official Build) (64-bit)**

System:

**Node version: 18
Platform: Windows**

**Comment by silviyaboteva** [comment] 2024-08-12 05:56
Hello @Genesis671230,
I cannot reproduce the problem with `v8.0.0` and latest `v8.2.0`. Here is the demo from our documentation along with the exported PDF file for reference:

Demo: https://stackblitz.com/edit/react-3y7cyu-1tfxff?file=app%2Fshared-ed-content.ts
Exported PDF: [editor.pdf](https://github.com/user-attachments/files/16577844/editor.pdf)

Please try to update to the latest version and test again. If you still reproduce the issue please don't hesitate to open a ticket in our [support system](https://www.telerik.com/account/support-tickets). In the ticket, it will be in great help if you attach a reproducible demo so that we can investigate further.

**Closed by silviyaboteva** 2024-08-12 05:56 UTC

**Comment by Genesis671230** [comment] 2024-08-12 08:21
> Hello @Genesis671230, I cannot reproduce the problem with `v8.0.0` and latest `v8.2.0`. Here is the demo from our documentation along with the exported PDF file for reference:
> 
> Demo: https://stackblitz.com/edit/react-3y7cyu-1tfxff?file=app%2Fshared-ed-content.ts Exported PDF: [editor.pdf](https://github.com/user-attachments/files/16577844/editor.pdf)
> 
> Please try to update to the latest version and test again. If you still reproduce the issue please don't hesitate to open a ticket in our [support system](https://www.telerik.com/account/support-tickets). In the ticket, it will be in great help if you attach a reproducible demo so that we can investigate further.

That yet persist.


Although i would reconsider the major issue when i try to export the pdf with arabic content. It result in below content

"E/’13 ’D%E’1’* ’DH7FJ)
FEH0, 1BE (9)
’DE,E9: lblCampus ’DE/13): lblSchool
*F(JG .7J DD7’D( (9/ ’D*F(JG ’D4AGJ
’DE3*4’1 ’D#C’/JEJ \ ’D#.5’&J ’D’,*E#*9G/ #F’
’3E ’D7’D(: lblStudentName ’D5A: lblGrade
&-G’. E/13) HDH’ (’D’D*23) (EH,( HAJ -’D)F E1) 4AGJK’*E *-0J1J #C+1 E 3J’3) BHAJE’ J*9DB (3DHCJ’*J ’D3D(J) ’D*’DJ):
1. &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&.
2. &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&.
3. &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&.
H9DI 0DC #B1.
: lblStudentName :
&&&&&&&&&&&&&&&
’3E ’D7’D( ’D*HBJ9
’9*E’/ E3’9/ 1&J3 ’DE/13)
5/1 (*’1J. : / / .
(J,( %.7’1 HDJ ’D#E1 (EH,( F3.) EF ’D*F(JG ’DEC*H( HJ,( ’D’-*A’8 (F3.) EFG AJ E’D7’D(
HF3.) #.1I D/I ’DE3*4’1 ’D#C’/JEJ / ’D#.5’&J ’D’,*E’9J).
*E %.7’1 HDJ ’D#E1  ’D’3E.... .......... ..................... .................................... ......... ............. ................’DHB*: &&&&&&&&&&&&&&&&&&&&&&&......................
J-B DD7’D( HHDJ #E1G ’D’9*1’6 9DI G0’ ’D%,1’! AJ :6HF 7 #J’E EF *’1J. 5/H1 B1"


I dont understand why this behavior persisit and how to solve this. please share any insights how to export arabic content correctly


<p><strong>نموذج رقم (9)</strong></p>
<p>المجمع: lblCampus المدرسة: lblSchool</p>
<p><strong>تنبيه خطي للطالب بعد التنبيه الشفهي</strong></p>
<p>المستشار الأكاديمي \ الأخصائي الاجتماعي \ لجنة إدارة السلوك</p>
<p>أتعهد أنا</p>
<p>اسم الطالب: lblStudentName الصف: lblGrade</p>
<p>بالالتزام بقواعد السلوك ولوائحها. وفي حالة ارتكاب مخالفة، سأكون مسؤبالنظر إلى ذلك، تم تحذيري أكثر من مرة شفهيًا فيما يتعلق بسلوكياتي السلبية التالية:</p>
<ol>
<li><p>…………………………………………………………………………………………….</p>
</li>
<li><p>…………………………………………………………………………………………….</p>
</li>
<li><p>………………………………………………………………………………………….</p>
</li>
</ol>
<p>وعلى ذلك أقر.</p>
<p><strong>اسم الطالب</strong>: lblStudentName &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<strong>التوقيع</strong>: ………………………………………</p>
<p><strong>اعتماد مساعد رئيس المدرسة</strong></p>
<p>صدر بتاريخ : / / .</p>
<p>(يجب إخطار ولي الأمر بموجب نسخة من التنبيه المكتوب، ويجب الاحتفاظ بنسخة منه في ملف الطالب ونسخة أخرى لدى المستشار الأكاديمي / الأخصائي الاجتماعي).</p>
<p>تم إخطار ولي الأمر ، الاسم: ........................................... صلة القرابة: .............................................. .......... رقم الموبايل: ............................................... .............................. تاريخ المكالمة: .............................................. ............................. الوقت: ……………………………………………………………......................</p>
<p>يحق للطالب وولي أمره الاعتراض على هذا الإجراء في غضون 7 أيام من تاريخ صدور قرار اللجنة.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>"


This is my arabic content
Thank you
