### ISSUE TITLE
[Grid] Resizing a column causes list to scroll up

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1664] opened 2023-08-11 07:50 UTC
Can be reproduced in this demo [https://www.telerik.com/kendo-react-ui/components/grid/columns/resizing/](https://www.telerik.com/kendo-react-ui/components/grid/columns/resizing/)
Steps to reproduce:
1. scroll down the vertical scrollbar to the end
2. click and hold the column to resize
3. then move the mouse down

https://github.com/telerik/kendo-react/assets/108671796/0b07c5c5-7a3b-4570-a99d-256e61b0a3b9

Related to #1437
Reported in Ticket ID: 1619466

**Comment by WissamProgress** [comment] 2024-01-12 12:19
Another bug that is related to it where a single resize scrolls the Grid to the top - https://github.com/telerik/kendo-react/issues/1850

Ticket ID: 1636997

**Comment by zdravkov** [comment] 2024-07-15 06:34
The issue is fixed in the latest 'dev' version of KendoReact and will be added to the next official release.

**Closed by zdravkov** 2024-07-15 06:34 UTC
Labels: Bug, pkg:Grid, SEV: High, KendoReact
