### ISSUE TITLE
Internationalisation - First day of week does not affect Calendar until re-render

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#998] opened 2021-07-12 03:53 UTC
## I'm submitting a...
* Bug report 

## Current behavior
First day of week override does not take effect until the Calendar component is unloaded and reloaded. I haven't tested other components but it may also be an issue there too.

## Expected behavior
First day of week will work immediately.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-k7l92u

1. The page will load with Sunday as first day of the week.
2. Click the rerender button.
3. Monday will become the first day of the week.

## What is the motivation or use case for changing the behavior?
We allow users to customise first day of the week in our application - users have complained that the feature isn't working correctly.

## Environment

Browser:
- Chrome (desktop) version 91.0.4472.124 (Official Build) (64-bit)

System:
- Platform: Windows

I found a temporary work around that I placed (commented out) in main.jsx, but I'm not sure what side effects this may cause.

**Comment by kspeyanski** [comment] 2021-09-02 07:18
Hello @GeoMarkou,

Thank you for providing a reproduction example.

The different `firstDay` on the initial render is due to the dynamic change in the `CustomIntlProvider`. I've further extended the example to provide the correct `firstDay` even on the first day:

https://stackblitz.com/edit/react-k7l92u-t8skos?file=app/main.jsx

I'm closing this issue for now, but please let me know if you have any feedback.

**Closed by kspeyanski** 2021-09-02 07:18 UTC
Labels: bug, pkg:dateinputs
