### ISSUE TITLE
Grid: Reordering the group fields in the group container works only with initial group expressions and breaks if you start with no groups

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1484] opened 2023-02-03 07:48 UTC
If there are initial group expressions in the Grid, it is possible to reorder the fields in the group drag container or to add new fields at specific position:
 - https://stackblitz.com/edit/react-vbckbt?file=app%2Fmain.jsx

However, if there are no initial groups or if the grouping is cleared, the reordering of the fields breaks and it is no longer possible to add a field to a specific position:
 - https://stackblitz.com/edit/react-snrpzx-vtsih4?file=app%2Fmain.tsx

In the second example you can add two fields to the grouping and you will notice that they can't be reordered, nor you can specify where to put the new field

**Comment by chaptastic** [comment] 2023-03-09 16:35
Is there an update or estimate on a fix for this issue? We're seeing the same thing and have a significant feature using the grid component nearing release and this is going to be a blocker.

**Comment by zdravkov** [comment] 2023-03-10 06:14
Hey @chaptastic.

Thank you for reaching out!
The issue is fixed in our latest 'dev' version and you can test it here - https://stackblitz.com/edit/react-snrpzx-twvmor?file=package.json
We are going to release an official version in in the first half of the next week so you will have it there, too.

Greetings,
Plamen

**Closed** 2023-03-20 09:33 UTC
Labels: bug, pkg:grid, Priority 1, SEV: Blocking
