### ISSUE TITLE
[Bug][Grid] Editable row with custom cell throws an error when clicked

### ISSUE THREAD

**Issue by Yanko-Georgiev** [telerik/kendo-react#2495] opened 2024-09-16 10:35 UTC
## I'm submitting a...
* Regression report 

## Current behavior
Currently, in version `8.2.0`, when having an editable column and a column with a custom cell in the Grid, clicking a row throws an error. In version `8.1.1`, the Grid behaves as expected. Whereas in `8.2.0` it throws the following error:

<img width="722" alt="Screenshot 2024-09-16 at 13 33 32" src="https://github.com/user-attachments/assets/776a70b9-a4ae-4966-b253-18962ae7acf7">

## Expected behavior
Clicking a row should properly focus it and enter the edit mode.

## Minimal reproduction of the problem with instructions
  1. Open this StackBlitz demo: https://stackblitz.com/edit/react-gwwffu?file=app%2Fapp.tsx,package.json.
  2. Click inside a grid row.
  3. Notice an error is thrown instead of focusing the row.

Related to Ticket: 1664251

**Comment by iadnonov** [comment] 2024-09-17 11:24
The issue is fixed in the latest develop version of the package: v8.3.0

Can be tested in the following example: https://stackblitz.com/edit/react-gwwffu-isavqr?file=package.json

**Closed by iadnonov** 2024-09-17 11:24 UTC
Labels: Bug, pkg:Grid, SEV: High, KendoReact, Regression
