### ISSUE TITLE
[Bug][TreeList] Columns become highlighted after column reording

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#2387] opened 2024-07-17 07:39 UTC
## I'm submitting a...

* Bug report 

## Current behavior
When reordering a column in the TreeList, the columns become highlighted and cannot be reordered again after the initial attempt. This occurs in version 8.1.1

## Expected behavior
Reordering should always work and the columns should not be highlighted

## Minimal reproduction of the problem with instructions
1. Open the following example: https://stackblitz.com/edit/react-vw75cl?file=app%2Fmain.tsx
2. Reorder the Name column and observe how it is highlighted
3. Try to reorder again and notice that you can't

Reported in Ticket ID: 1658420

**Comment by PekoPPT** [comment] 2024-07-24 07:12
The issue is fixed and will be available in the next official version of Kendo React which should be released in the next two weeks.

**Closed by PekoPPT** 2024-07-24 07:12 UTC
Labels: Bug, pkg:Treelist, KendoReact, Regression, triaged
