### ISSUE TITLE
[Bug][DatePicker] Editing the value in the DateInput after refocusing the field doesn't correctly edit the date

### ISSUE THREAD

**Issue by Yanko-Georgiev** [telerik/kendo-react#2527] opened 2024-09-24 11:32 UTC
## I'm submitting a...
* Bug report 

## Current behavior
When there is a value inside the DateInput typing a new one doesn't overwrite the existing one but continues to write after it.

## Expected behavior
Typing a value after refocusing the field should overwrite the value instead of continuing to write it.

## Minimal reproduction of the problem with instructions
  1. Open this Stackblitz example: https://stackblitz.com/edit/react-nc4vd1?file=app%2Fapp.jsx
  2. In the day field type 2, then focus out of the field.
  3. Focus again on the day field and type 23.
  4. Notice that the value is 3, instead of 23.

Reported in Ticket: 1664990

**Comment by iadnonov** [comment] 2024-10-23 07:56
The issue is resolved in the latest develop version **9.0.0-develop.6**, and will be available in the next official version of the package.

Can be tested in the following example: https://stackblitz.com/edit/react-nc4vd1-fpkwbf?file=package.json

**Closed by iadnonov** 2024-10-23 07:56 UTC
Labels: Bug, pkg:Dateinputs, SEV: Medium, KendoReact
