### ISSUE TITLE
DateRange Picker component: Ensures ARIA attributes are allowed for an element's role

### ISSUE THREAD

**Issue by dejimarquis** [telerik/kendo-react#370] opened 2019-10-30 18:44 UTC
## I'm submitting a...

* Suggestion for improvement

## Current behavior

Given I have a Date Range Picker component in my web application, when I run FastPass using Accessibility Insights for Web, I get the follow error message:
**Fix the following:
ARIA attributes are not allowed: aria-valuemin="-2208960000000" aria-valuemax="4102387200000" aria-valuetext="9/29/2017" aria-valuenow="1506712202695" aria-expanded="false"**

## Expected behavior

Given I have a Date Range Picker component in my web application, when I run FastPass using Accessibility Insights for Web, then I should not receive the following error message above

## Minimal reproduction of the problem with instructions

[https://stackblitz.com/edit/react-gxxd4k?file=app/main.jsx](url)

## What is the motivation or use case for changing the behavior?

This enables components in your library be accessible.

**Comment by kspeyanski** [comment] 2019-10-31 05:59
Hello @dejimarquis ,
Thank you for reporting this.

I'll need some time to dig in deeper, since those `aria-*` attributes are being used by screen readers to pronounce the value and indicate the minimum and maximum values allowed. 

This being said, i'm not sure we can remove them, but rather investigate why the mentioned tool shows them as an errors. I can confirm that the issue is reproducible on my side with FastPass Chrome extension.

I'll get back to you once i found something.

Greetings

**Comment by dejimarquis** [comment] 2019-10-31 18:01
Thanks for looking into this! Will be looking forward to your updates

**Comment by vladimirivanoviliev** [comment] 2019-11-02 17:04
Just as a side note - there is example of using these attributes in W3C website for DatePicker with spin buttons [(link)](https://www.w3.org/TR/wai-aria-practices-1.1/examples/spinbutton/datepicker-spinbuttons.html), but the example shows validating smaller numbers like date, year.

**Comment by kspeyanski** [comment] 2019-11-04 14:28
From what i could test on my side, adding the `role="spinbutton"` to the `DateInput` (the input element inside the `DatePicker`), allows setting the `aria-valuemin`,  `aria-valuemax` and `aria-valuetext`.

As a next step, we will be double-checking if this `role` applies to the `DateInput` component, and apply it if this is correct.

**Comment by dejimarquis** [comment] 2019-11-05 21:18
Thanks for looking into this @kspeyanski ! I will be waiting on results of your next steps.

**Comment by kspeyanski** [comment] 2019-11-11 07:14
Hello @dejimarquis ,

We've published a `dev` version of the `@progress/kendo-react-dateinputs` package, and i can no longer reproduce the problem.

For the full list of changes in the `3.7.0@dev` version, please refer to the changelog:
https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#toc-370-dev201911061216 
You can install it with the following command:
```sh
npm install @progress/kendo-react-dateinputs@dev
```

Turns out `aria-valuemin`/`max`/`now` is only available on elements with role `spinbutton`.

I'll be closing this issue for now, but please let me know if you experience any other accessibility issues with any of the KendoReact components.

**Closed by kspeyanski** 2019-11-11 07:14 UTC
Labels: discussion, enhancement
