### ISSUE TITLE
Calendar component displays wrong days for french and spanish (maybe other languages too)

### ISSUE THREAD

**Issue by gabsoftware** [telerik/kendo-react#2310] opened 2024-06-17 10:03 UTC
## I'm submitting a...
* Regression report 

## Current behavior
Switching to french or spanish locale show wrong day names in the Calendar component.
See https://www.telerik.com/kendo-react-ui/components/dateinputs/globalization/ for example, it starts at "tuesday".
This showed correctly in a previous version.

## Expected behavior
Display the correct day names.

## Minimal reproduction of the problem with instructions

  1. Open https://www.telerik.com/kendo-react-ui/components/dateinputs/globalization/
  2. See that it starts with "MA" instead of "LU"

## What is the motivation or use case for changing the behavior?
Don't know

## Environment

Package versions:
latest

Browser:

- Firefox version latest

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:  

The function weekNames in file kendo-react-private\packages\dateinputs\src\calendar\components\ViewList.tsx was changed recently and it calls shiftWeekNames twice now (once in weekNames function, and once in WeekNamesService.getWeekNames).

So the issue only appears for locales that start with another day than Sunday.

**Comment by gabsoftware** [comment] 2024-06-17 10:04
![2024-06-17 11 58 53 image](https://github.com/telerik/kendo-react/assets/1510039/db8c1593-802e-4949-8f73-4dd95c269297)

**Comment by gabsoftware** [comment] 2024-06-17 11:29
The commit that introduced the change is #882fc0b30c5364a300b8722a18378527ee197746 "chore: start using weekservice in Calendar ViewList component"

**Comment by PaskalevStoyan** [comment] 2024-06-19 08:15
Hi @gabsoftware,

Thanks for bringing this to our attention. 

Indeed this is a bug and as it seems its a regression. We will treat this with top priority and a fix will be provided soon.

I apologies for any inconvenience caused!

**Comment by PaskalevStoyan** [comment] 2024-06-19 11:32
Hi @gabsoftware,

We've managed to resolve the issue and a fix is introduced in `version 8.1.0-develop.17` of the kendo-react-dateinputs.

**Closed** 2024-06-19 11:32 UTC
Labels: Bug, pkg:Dateinputs, Regression

**Comment by gabsoftware** [comment] 2024-06-19 11:51
Okay, thank you, but when will it land in the production release?

**Comment by PaskalevStoyan** [comment] 2024-06-19 12:09
We continuously release official versions within every few weeks.  In this line of words, I will come back to this issue to leave a comment when we do so and inform you.

**Comment by PaskalevStoyan** [comment] 2024-06-19 13:24
The last version that did not produce the issue is `v7.4.0`

**Comment by PaskalevStoyan** [comment] 2024-06-27 07:18
Hi @gabsoftware,

I'm, happy to say that we've released and official version and this bug fix is included in it. The new version of the KendoReact components is `v8.1.0`.
