### ISSUE TITLE
[Bug][Window] Unwanted text selection occurs when resizing horizontally

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#2326] opened 2024-06-25 07:45 UTC
## I'm submitting a...

* Bug report 

## Current behavior
 currently when a Window component is resized, in some moment all text elements get selected.

## Expected behavior
When resizing the Window nothing gets selected as it is in Kendo UI Angular.

## Minimal reproduction of the problem with instructions
1. Open the following example: https://stackblitz.com/edit/react-whyw3s?file=app%2Fmain.tsx
2. Resize the Window horizontally
3. Observe how the text gets selected

## Package version
Occurs in 8.0.0 onward 

Reported in Ticket ID: 1656159

**Comment by PekoPPT** [comment] 2024-07-24 07:10
The issue is fixed and the fix will be available in the next official version of Kendo React which should be released in the next two weeks.

**Closed by PekoPPT** 2024-07-24 07:10 UTC
Labels: Bug, pkg:Dialogs, KendoReact, Regression
