### ISSUE TITLE
NumericTextBox percentage format have two issues.

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#5] opened 2018-02-06 15:50 UTC
In this demo: https://www.telerik.com/kendo-react-ui/components/inputs/numerictextbox/formats/
* Deleting the percentage sign results in 100%.
* The user is not able to delete the first digit

**Comment by Xizario** [comment] 2018-03-06 09:17
* Typing `5` after selection all the text, including the percentage sign, results in `500%` rather than `5%`

**Comment by mwolfhoffman** [comment] 2018-10-24 17:35
@Xizario I had the same issue with kendo-angular. Kendo isn't documenting this but the following SO solved my issue. Try it out. 
https://stackoverflow.com/questions/49908229/angular-4-kendo-numerictextbox-percentage-issue

**Comment by vladimirivanoviliev** [comment] 2020-01-15 11:22
Fixed in latest dev version `3.10.0-dev.202001150733`.

**Comment by rimmesbe** [comment] 2020-04-20 15:57
So this still seems to be an issue when using percentage formats with decimal places:
`<NumericTextBox onChange={this.setPercentage} name='PotentialRebate' format="p1" defaultValue={0} />`

When selecting the whole value including the % it jumps to 100% when typing a number.
format="p" (works fine), format="p1" (jumps to 100%).

Looking for a workaround, thanks.

**Comment by vladimirivanoviliev** [comment] 2020-04-23 14:41
I can confirm that this is an issue - only percent format w/o precision ('p') is handled. Currently there is no workaround, however we will try to fix it before next official release (mid May).

**Comment by Xizario** [comment] 2020-04-29 09:30
Fixed in 3.13.0

**Comment by simonssspirit** [comment] 2020-06-18 07:06
The issue seems to still persist on paste. If we write 1, it will make it 1.00% but if we paste 1 it will make it 100.00%.

**Comment by vladimirivanoviliev** [comment] 2020-07-10 06:41
Fixed in latest dev version.

**Comment by vladimirivanoviliev** [comment] 2020-07-13 12:37
Released with 3.16.0-dev.202007130614.

**Closed by vladimirivanoviliev** 2020-07-13 12:37 UTC
Labels: bug, pkg:inputs
