### ISSUE TITLE
TableGrid OData Implementation: StartWith and EndWith Filter for Dates

### ISSUE THREAD

**Issue by andreastoermer** [telerik/kendo-react#509] opened 2020-03-12 06:31 UTC
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Current behavior
I have create a datefilter (without odata everything works) and want to use it with odata. This filter use the entered date and return everything which is newer (or for another filter older) than the entered date.

A function to have this in odata is "close_dt ge DateTime'2012-05-29T09:13:28'". But when i try to use it in the custom filter i get the following error message:

`TypeError: filterOperators(...) is not a function`

## Expected behavior
Have a working ge Filter for DateTime in OData inside of Kendo Grid.

## What is the motivation or use case for changing the behavior?

Can you custom odata filter to only show entries which are created at the specific or are newer.

## Environment

Package versions:

```
"@progress/kendo-data-query": "1.5.2",
"@progress/kendo-drawing": "1.13.7",
"@progress/kendo-react-animation": "3.11.0",
"@progress/kendo-react-buttons": "3.11.0",
"@progress/kendo-react-data-tools": "3.11.0",
"@progress/kendo-react-dateinputs": "3.11.0",
"@progress/kendo-react-dropdowns": "3.11.0",
"@progress/kendo-react-grid": "3.11.0",
"@progress/kendo-react-inputs": "3.11.0",
"@progress/kendo-react-intl": "3.11.0",
"@progress/kendo-react-layout": "3.11.0",
"@progress/kendo-react-treeview": "3.11.0",
```

Browser:

- Firefox version 74.0
But it's not a browser problem

System:
- TypeScript version: 3.8.3 
- Node version: 12.16.1  
- Platform:  Windows

**Comment by simonssspirit** [comment] 2020-03-13 08:22
@andreastoermer 
This sounds as a case discussed here: https://github.com/telerik/kendo-react/issues/355

Please check it and advise if the issue is different.

**Comment by simonssspirit** [comment] 2020-04-27 12:06
Closed as duplicated.

**Closed by simonssspirit** 2020-04-27 12:06 UTC
Labels: pkg:grid
