### ISSUE TITLE
[Documentation][Grid] Custom cells demo throws error upon canceling a newly created row

### ISSUE THREAD

**Issue by Yanko-Georgiev** [telerik/kendo-react#2361] opened 2024-07-10 06:55 UTC
## I'm submitting a...
* Bug report 

## Current behavior
When clicking on cancel in newly added rows an error is thrown.
```
ERROR
Cannot read properties of undefined (reading 'inEdit')
TypeError: Cannot read properties of undefined (reading 'inEdit')
    at http://localhost:3000/static/js/bundle.js:214:43
    at Array.filter (<anonymous>)
    at App (http://localhost:3000/static/js/bundle.js:214:29)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:33644:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:37211:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:38930:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:23900:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:23944:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:24001:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:43899:11)
```
## Expected behavior
The demo should work without errors.

## Minimal reproduction of the problem with instructions
  1. Open this demo: https://www.telerik.com/kendo-react-ui/components/grid/cells/#toc-edit
  2. Click cancel.
  3. The above error occured.

**Comment by PekoPPT** [comment] 2024-07-10 07:21
The reported issue is not a bug with the component but is triggered by an inconsistency in the demo. We will prioritize the demo fix. [Here is a modified version of the example](https://stackblitz.com/edit/react-uhrgyl?file=app%2Fapp.jsx) in which the error doesn't appear.

**Comment by WissamProgress** [comment] 2024-07-15 04:48
Fixed in the develop branch - https://www.telerik.com/kendo-react-ui-develop/components/grid/cells/#toc-edit
It will soon be available on the official page.

**Closed by WissamProgress** 2024-07-15 04:48 UTC
Labels: pkg:Grid, Documentation, KendoReact
