### ISSUE TITLE
Unresponsive Grid buttons when contained in a Sortable item 

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1135] opened 2021-11-12 09:34 UTC
When having a Sortable component that generates a grid within each item clicking on a row item blocks the click on a button inside the grid. 

Ticket ID: 1542541 (the ticket contains a Stackblitz example)

**Comment by kdikov82** [comment] 2022-01-24 12:32
We can add "filter" or "exclude" option for the Sortable that accepts an array of CSS selectors and if the target matches any of the selectors, do not execute the Sortable logic for starting the dragging or preventing the default events within the sortable items:

const selectors = [".k-button", ".my-class"];
...
< Sortable exclude={selectors}/>

**Comment by vladimirivanoviliev** [comment] 2022-02-10 13:22
I'm more for the second option as it would be much easier to define 1 element like drag handle for dragging. @Xizario what do you think ?

**Comment by Xizario** [comment] 2022-02-10 14:13
You can conditionally preventDefault of the [onDragStart](https://www.telerik.com/kendo-react-ui/components/sortable/api/SortableOnDragStartEvent/) event based on the target element and achieve the drag handler. 
Let say your sortable UI is something like:
```jsx
    <div
      ref={forwardRef}
      {...attributes}
      style={{ ...getBaseItemStyle(isActive), ...style }}
      className={classNames.join(' ')}
    >
      <span className="dragHandler">(Some icon here maybe for the drag handler)</span>
      {dataItem.text}
    </div>
```

```jsx
  const onDragStart = (event) => { 
    if ((event.element.className !== 'dragHandler')) {
      event.preventDefault(); 
    } 
  };
```
Adding this as additional property is not huge time saver and is more limited in function.

**Comment by Micah-S** [comment] 2022-02-16 00:59
> You can conditionally preventDefault of the [onDragStart](https://www.telerik.com/kendo-react-ui/components/sortable/api/SortableOnDragStartEvent/) event based on the target element and achieve the drag handler. Let say your sortable UI is something like:
> ...
> Adding this as additional property is not huge time saver and is more limited in function.

Maybe there's something else going on, but the issue is still present here:
https://stackblitz.com/edit/react-4fwts6-eusnbn?file=app/main.jsx

**Comment by vladimirivanoviliev** [comment] 2022-02-17 08:40
After further investigation it appears that the reason for current behavior is redrawing the element on blur to nested components which is incorrect. The issue is now fixed on our side and the fix will be available with next dev versions.

**Closed** 2022-03-11 14:50 UTC
Labels: bug, pkg:sortable
