### ISSUE TITLE
Material Floating Labels Appears Incorrectly When Autofilled

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#172] opened 2019-01-24 01:15 UTC
## I'm submitting a...
* Bug report

## Current behavior
Material floating labels overlaps the text on Chrome in autoComplete forms.

## Expected behavior
Floating label initially renders above the input if it is autoCompleted.

## Minimal reproduction of the problem with instructions
I had trouble getting the Editor to display the "save my password" prompt so I recommend the Viewer.

Editor:
https://stackblitz.com/edit/react-bcowxm

Viewer:
https://react-bcowxm.stackblitz.io

1. Type anything into the username and password.
2. Press submit, remembering to click "save my password" when prompted.
3. Refresh the page, the fields should autofill with the yellow background on page load.
4. Clicking anywhere on the page will make the fields realise they have content and the labels will then go to their correct spot.

![image](https://user-images.githubusercontent.com/12272970/51647705-caa3cd00-1fcd-11e9-83cf-a011f62c4ce4.png)

## What is the motivation or use case for changing the behavior?
We just changed our login page to use Kendo Material design with floating labels, but they don't display correctly on Chrome when returning to the site. They work correctly in Firefox so maybe it's something to do with the way Chrome autofills.

## Environment
Browser:
- Chrome (desktop) Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by silviyaboteva** [comment] 2019-10-28 11:28
The issue is fixed with the upcoming `v3.7.0`. 
Demo: https://stackblitz.com/edit/react-bcowxm-uxwptk?file=index.js

**Closed by silviyaboteva** 2019-10-28 11:28 UTC
Labels: bug, pkg:inputs
