### ISSUE TITLE
[Bug][Popup] Scale property not working & breaks the popup positioning when set

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-react#2320] opened 2024-06-21 10:06 UTC
## I'm submitting a...
* Bug report 

## Current behavior
The **scale** property of the Popup component is not working as described in the API documentation. When the property is set, the following two issues appear:
1. The position of the Popup is incorrect
2. The Popup is not scaled as it is expected to be

* The above affects also the other KendoReact components like the DropDowns. 

## Expected behavior
Setting the **scale** property should not break Popup's positioning and should scale the **Popup's** content

## Minimal reproduction of the problem with instructions
1. Open [this StackBlitz example](https://stackblitz.com/edit/react-1fwqdr-gbhdbf?file=app%2Fmain.jsx)
2. See the scaled Button component and the incorrect Popup position

The result should look as follows but scaled by 0.7
<img width="145" alt="image" src="https://github.com/telerik/kendo-react/assets/41293735/b37beb2a-e7d7-47b9-94db-cadc5a7388b2">

**Comment by kdikov82** [comment] 2024-09-13 06:52
The same issue is observed with the "zoom" property:
https://stackblitz.com/edit/react-jsc8pe-aprjwg?file=app%2Fapp.tsx,index.html

**Comment by kspeyanski** [comment] 2024-11-04 07:05
After further investigation, it turns out that this is not a bug in the component, but rather an implementation detail which is not taken into consideration when building the demo.

The `Popup` is being appended to the `document.body` by default, meaning any `scale` or `zoom` properties applied to an inner elements would not work correctly unless a) The popup sets `appendTo={null}` to disable appending to the body, or b) The `appendTo={containerWithScale}` is set to the actual container which has the scale/zoom set.

 ## With `scale`:
1) When the `appendTo` is set to `null`, thus the Popup's DOM element is rendered in the same place in as it's react component: https://stackblitz.com/edit/react-1fwqdr-sczmzt?file=app%2Fmain.jsx

2) When the `appendTo` is set to the container with scale/zoom: https://stackblitz.com/edit/react-1fwqdr-p6xmvd?file=app%2Fmain.jsx

More on the `appendTo` property in the [PopupProps' API](https://www.telerik.com/kendo-react-ui/components/popup/api/PopupProps/#toc-appendto)

## With `zoom`:

It's stated in the [component's api](https://www.telerik.com/kendo-react-ui/components/popup/api/PopupProps/#toc-scale) that automatically calculating the `scale`/`zoom` is unreliable and thus manually setting it is required to work. This being said since the demo is using a `DropDownList` with Popup inside, and not the `Popup` component directly, we must use the `PopupPropsContext` to set the `scale` to be in-sync with the `zoom` style:

https://stackblitz.com/edit/react-jsc8pe-caqxxx?file=app%2Fapp.tsx

Closing the issue for now, but feel free to re-open if the component is still not behaving as expected.

**Closed by kspeyanski** 2024-11-04 07:05 UTC
Labels: Bug, pkg:Popup, SEV: High, KendoReact, triaged
