### ISSUE TITLE
Gantt task on the wrong position after filtering.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#804] opened 2020-12-08 14:39 UTC
Gantt task on the wrong position after filtering.

This can be observed in the following example:

https://stackblitz.com/edit/react-6rfhx5?file=app%2Fmain.jsx

1) Expand items:

![image](https://user-images.githubusercontent.com/11087921/101497106-482f1700-3973-11eb-9d27-38e94037356e.png)
****

2) Type 10 in the filter:

![image](https://user-images.githubusercontent.com/11087921/101497263-76145b80-3973-11eb-8192-4e67446ec26e.png)

3) Clear the text and noticed the task is in a new position:

![image](https://user-images.githubusercontent.com/11087921/101497523-becc1480-3973-11eb-86f6-7211faf86acc.png)

**Comment by vladimirivanoviliev** [comment] 2020-12-08 21:22
I can confirm that this issue is already **resolved** on our side and the fix will be released with the upcoming Keyboard navigation feature, expected to be available in the following two weeks. 
The reason for this behavior is that previously the Gantt component used level-index based `key` for it's rows which was not unique. In latest version the component the task id is used for this purpose.

**Closed** 2021-01-21 13:16 UTC
Labels: bug, pkg:gantt
