### ISSUE TITLE
Grid component virtual scrolling when using Detail Rows

### ISSUE THREAD

**Issue by mdakovac** [telerik/kendo-react#367] opened 2019-10-29 14:11 UTC
Is this possible and how? Furthermore, is it possible to use virtual scrolling when DetailComponent is an element of variable height, for example another table.

**Comment by simonssspirit** [comment] 2019-11-06 12:22
Currently, the Grid uses the rowHeight to correctly work with virtual scrolling.

With details rows, the height of the rows can vary a lot.

This is why we have an enhancement for a detailRowHeight for these cases:

https://github.com/telerik/kendo-react/issues/361

For now, we can suggest using it with endless scrolling as shown in the example, it is not as virtual scrolling, but it can help with large data sets:

https://stackblitz.com/edit/react-ehct6l-auzbfb?file=app/main.jsx

**Comment by simonssspirit** [comment] 2019-11-06 12:23
duplicate of https://github.com/telerik/kendo-react/issues/361

**Closed by simonssspirit** 2019-11-06 12:23 UTC
