### ISSUE TITLE
PanelBar doesn't use the className prop

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#117] opened 2018-11-07 02:48 UTC
## I'm submitting a...

* Bug report 

## Current behavior
PanelBar doesn't use the className prop.

## Expected behavior
Setting className prop should render a html element with the class specified.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-xg83fr

1. In main.js you can see I've set <PanelBar className='test'> and  <PanelBarItem className='testInner'>
2. Clicking the button shows that only the PanelBarItem has a className set, the PanelBar doesn't (you can also inspect-element on the PanelBar)

## What is the motivation or use case for changing the behavior?
We have different styling for when a PanelBar is single or multi select. Specifying the className would be a useful way to distinguish them.

## Environment

Browser:

- Chrome (desktop) version 70.0.3538.77 (Official Build) (64-bit)

**Comment by vladimirivanoviliev** [comment] 2018-11-07 10:14
Hi, the issue is now fixed on our side and the fix will be released with the next official release.

**Comment by Xizario** [comment] 2019-03-25 07:40
Fixed in `2.8.0`

**Closed by Xizario** 2019-03-25 07:40 UTC
Labels: bug, pkg:layout
