### ISSUE TITLE
Scheduler remove not triggering

### ISSUE THREAD

**Issue by Padhraic** [telerik/kendo-react#419] opened 2019-12-13 07:16 UTC
## I'm submitting a...
* Bug report

## Current behavior
Delete of item not triggering `onDataChange`

## Expected behavior
`onDataChange` event should trigger with `event.deleted` array containing the events to be deleted.
In StackBlitz [sample](https://stackblitz.com/edit/react-fyvmev) event should be logged with `event.deleted` set to deleted item.

## Minimal reproduction of the problem with instructions
StackBlitz with issue [here](https://stackblitz.com/edit/react-fyvmev)
1. Mouse over the X in top right hand corner of event.
2. Click -> `onDataChange` event should trigger.

Changing `editable={true}` in the scheduler component has same result, no event fired.
Same for recurring event and single event.

## Environment
Package versions:
    "@progress/kendo-date-math": "1.5.0",
    "@progress/kendo-drawing": "1.6.0",
    "@progress/kendo-react-animation": "3.9.0",
    "@progress/kendo-react-buttons": "3.9.0",
    "@progress/kendo-react-common": "3.9.0",
    "@progress/kendo-react-dateinputs": "3.9.0",
    "@progress/kendo-react-dialogs": "3.9.0",
    "@progress/kendo-react-dropdowns": "3.9.0",
    "@progress/kendo-react-form": "^3.9.0",
    "@progress/kendo-react-inputs": "3.9.0",
    "@progress/kendo-react-intl": "3.9.0",
    "@progress/kendo-react-popup": "3.9.0",
    "@progress/kendo-react-scheduler": "3.9.0",
    "prop-types": "15.7.2",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-transition-group": "4.3.0"

Browser:
- Chrome (desktop) Version 79.0.3945.79 (Official Build) (64-bit)

System:
- TypeScript version: 3.4.5
- Node version: 6.5.0-next.0
- Platform:  Windows

**Comment by simonssspirit** [comment] 2019-12-16 06:58
@Padhraic 

I made a video and the deleted event was part of the deleted collection:

https://www.screencast.com/t/QGxlCmrZn5Eh

**Comment by Padhraic** [comment] 2019-12-16 08:47
@simonssspirit 
Thanks for your reply. Here is a screen recording of the issue happening on my machine when I use chrome Version 79.0.3945.79 (Official Build) (64-bit). 
The issue is not happening when I run the StackBlitz on Microsoft Edge. 
Perhaps the issue is caused by some kind of chrome security setting set for my domain.

![SchDeleteEvent_chrome](https://user-images.githubusercontent.com/10623235/70891868-73ff1180-202b-11ea-9509-7a12af7b2593.gif)

**Comment by simonssspirit** [comment] 2019-12-17 10:45
@Padhraic I noticed that the "X" is not getting clicked easily, on my end it works on a second on the third time.

@kspeyanski please take a look at this.

**Comment by kspeyanski** [comment] 2020-10-06 13:03
Thank you for your patience.

After revisiting this issue, i'm not able to replicate the described problem. I'll be closing this issue for now, but please feel free to reopen in if you manage to replicate it. I will greatly appreciate any further description on how to replicate it.

**Closed by kspeyanski** 2020-10-06 13:03 UTC
Labels: bug, pkg: scheduler

**Comment by kmbro** [comment] 2020-11-19 16:45
I am having issues with this as well. 

Specifically the reason my close is not working is because I am using a react router hash router, and the "x" to delete an event has `href="#"`

So I see the modal for about .2 seconds asking if i'd like to delete the event then my app navigates away.
I think this is a bug. Can you advise how you would fix it?
Thanks!

**Comment by kspeyanski** [comment] 2020-11-20 07:00
Hello @kmbro ,

I can confirm that this is a bug and it's related to the `href` attribute on the SchedulerItem. We will be deploying a fix shortly.

In the meantime may i suggest the following workaround:
```js
const CustomItem = (props) => {
  const handleClick =(event) => {
    event.syntheticEvent.preventDefault();
    if(props.onClick) {props.onClick(event);}
  }

  return <SchedulerItem {...props} onClick={handleClick} />
}
...
<Scheduler item={CustomItem} />
```

The above code will prevent the redirect when clicking the `x` button on the Scheduler Item.
Please let me know if you find this helpfull.

**Comment by kmbro** [comment] 2021-04-07 03:46
@kspeyanski this worked, thanks!

Still an issue in scheduler 4.5.0 unfortunately, but I am happy with this work around
