### ISSUE TITLE
Virtual scroll Grid scrollbar 'jump' when scrolling in Safari.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#847] opened 2021-02-05 08:19 UTC
Virtual scroll Grid scrollbar 'jump' when scrolling in Safari.

This can be observed in our demo:

https://www.telerik.com/kendo-react-ui/components/grid/columns/column-virtualization/

More details, with a video, can be found in the ticket: 1505316

**Comment by eakelb** [comment] 2021-07-26 14:08
We've ran into same issue even without column virtualization - just adding `scrollable={"virtual"}` breaks the grid in safari. As you can see in the video sometimes you can't even scroll to the top.

Example is basic virtual scroll usage from docs, section Getting Started: https://www.telerik.com/kendo-react-ui/components/grid/scroll-modes/virtual/
I limited data count to 10 to make the bug more clear

https://user-images.githubusercontent.com/21054555/127002552-97d3b67a-bf2d-4c39-8954-6ce2218c62ab.mov

**Comment by simonssspirit** [comment] 2021-08-05 04:50
reported again in 1530464

**Comment by simonssspirit** [comment] 2021-08-05 04:51
probably connected to : https://github.com/telerik/kendo-react/issues/1013

**Comment by simonssspirit** [comment] 2022-03-09 06:33
reported again in 1556806. Raising priority and moving to the ToDo list.

**Comment by zdravkov** [comment] 2022-12-14 06:52
Hi all,
We are currently investigating the issues with the 'jump' when scrolling in Safari but don't seem to observe it any more on Monterey , Safari - Version 16.1 (17614.2.9.1.13, 17614).  
Here is the [Stackblitz example](https://stackblitz.com/edit/react-jzumva-nzfqza) that we use and here is a short gif of one of our tests:
![jump-grid-safari](https://user-images.githubusercontent.com/9494406/207525199-2a60f683-dce3-4bf0-836c-28ffd4343dc3.gif)

Sometimes there is a small delay in the loading of the items, especially when scrolling up, yet this issue is considered a different one that will be addressed separately from this one. 

If you are still observing the unexpected 'jump' please let us know what else should we do or test to replicate it at our side.

Greetings,
Plamen

**Comment by ASmint** [comment] 2022-12-16 14:20
Hi @zdravkov 

The issue is still there when you try to scroll up.  It is not smooth enough and could stop scrolling or jump to the first row. 
You don't need to scroll to the middle of a list to see the issue
Please see my video. 

It is reproducible on Mac and iPad for me.  (version 16.1 (18614.2.9.1.12))


https://user-images.githubusercontent.com/20088480/208118350-12ed131b-6e62-4299-823f-13a821001ae1.mov

**Comment by zdravkov** [comment] 2022-12-19 06:44
Thanks @ASmint, for sharing you observations.

Yes, I can observe this, too. The initial 'jump' reported here was a bit different and I was addressing it, when saying it is not reproducible any more. 

We are currently, doing our best to improve the virtual scroll in may areas so we will do our best to fix this 'scroll up' behavior, too.

Greetings,
Plamen

**Comment by ASmint** [comment] 2022-12-19 09:59
@zdravkov Yes, the main issue now is not as bad as it was. But our target device is an iPad and users might not have it updated.  So for us, it is still actual.

**Comment by nstoychev** [comment] 2023-01-18 14:41
Fixed in version 5.10.0.

Note that grid's `rowHeight` prop is required now and the `pageSize`/`take` props need to be at least 2 times the count of the visible rows.

**Closed by nstoychev** 2023-01-18 14:41 UTC
Labels: bug, pkg:grid
