### ISSUE TITLE
"Warning: useLayoutEffect does nothing on the server[...]" appears when using Grid

### ISSUE THREAD

**Issue by NPeinPUS** [telerik/kendo-react#1841] opened 2024-01-09 06:52 UTC
## I'm submitting a...

* Bug report 

## Current behavior

When running the provided example [telerik/kendo-react-ssr](https://github.com/telerik/kendo-react-ssr) and accessing the website running at http://localhost:8000, this warning is thrown:
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at A:\kendo-react-ssr\node_modules\@progress\kendo-react-common\index.js:5:31432
    at pr (A:\kendo-react-ssr\node_modules\@progress\kendo-react-grid\index.js:5:13189)
    at Nt (A:\kendo-react-ssr\node_modules\@progress\kendo-react-grid\index.js:5:16423)
    at thead
    at table
    at div
    at div
    at dr (A:\kendo-react-ssr\node_modules\@progress\kendo-react-grid\index.js:5:11293)
    at div
    at div
    at X (A:\kendo-react-ssr\node_modules\@progress\kendo-react-grid\index.js:5:52889)
    at A:\kendo-react-ssr\node_modules\@progress\kendo-react-common\index.js:5:16178
    at div
    at R (A:\kendo-react-ssr\node_modules\@progress\kendo-react-tooltip\index.js:5:1940)
    at div
    at App (A:\kendo-react-ssr\src\App.js:35:52)
```

## Expected behavior

The warning doesn't show up.

## Minimal reproduction of the problem with instructions

1. clone the repository [telerik/kendo-react-ssr](https://github.com/telerik/kendo-react-ssr)
2. checkout branch "master/dependancy-update"
3. `yarn install`
4. `yarn build`
5. `yarn ssr`
6. navigate to http://localhost:8000 on a browser
7. check the output of `yarn ssr`

## What is the motivation or use case for changing the behavior?

It would be nice to be able to use Kendo Grids with Astro.

## Environment

Package versions:

```
kendo-react-ssr@0.1.0 A:\kendo-react-ssr
+-- @babel/preset-env@7.23.8
+-- @babel/preset-react@7.23.3
+-- @babel/register@7.23.7
+-- @progress/kendo-data-query@1.7.0
+-- @progress/kendo-date-math@1.5.12
+-- @progress/kendo-drawing@1.19.0
+-- @progress/kendo-inputs-common@3.1.0
+-- @progress/kendo-intl@3.1.1
+-- @progress/kendo-licensing@1.3.5
+-- @progress/kendo-popup-common@1.9.2
+-- @progress/kendo-react-animation@7.0.2
+-- @progress/kendo-react-buttons@7.0.2
+-- @progress/kendo-react-common@7.0.2
+-- @progress/kendo-react-data-tools@7.0.2
+-- @progress/kendo-react-dateinputs@7.0.2
+-- @progress/kendo-react-dialogs@7.0.2
+-- @progress/kendo-react-dropdowns@7.0.2
+-- @progress/kendo-react-grid@7.0.2
+-- @progress/kendo-react-inputs@7.0.2
+-- @progress/kendo-react-intl@7.0.2
+-- @progress/kendo-react-labels@7.0.2
+-- @progress/kendo-react-layout@7.0.2
+-- @progress/kendo-react-popup@7.0.2
+-- @progress/kendo-react-progressbars@7.0.2
+-- @progress/kendo-react-tooltip@7.0.2
+-- @progress/kendo-react-treeview@7.0.2
+-- @progress/kendo-theme-default@7.0.2
+-- @testing-library/jest-dom@6.2.0
+-- @testing-library/react@14.1.2
+-- @testing-library/user-event@14.5.2
+-- express@4.18.2
+-- ignore-styles@5.0.1
+-- react-dom@18.2.0
+-- react-scripts@5.0.1
+-- react-transition-group@4.4.5
+-- react@18.2.0
`-- rewire@7.0.0
```

Browser:

- Edge version 120.0.2210.121 (Official build) (64-bit) 

System:
- TypeScript version: 4.8.4 
- Node version: v21.2.0  
- Platform: Windows

**Comment by WissamProgress** [comment] 2024-01-11 12:13
@NPeinPUS Thank you for reporting this bug. Since it is reproducible only after updating the dependencies, I believe that it is caused by the new way we are calculating the random IDs that are passed to the id props, and aria attributes of the components. This is the case for versions 7.0.0 and above where we made all the components compatible with Next.js - https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#v7.0.0

We switched from using our internal guid function to use [React.useId](https://react.dev/reference/react/useId) when the used React version is 18 and above since the guid was causing a hydration error during SSR. For previous versions, we are using the guid without causing hydration errors, and we are using useLayoutEffect in the file where we apply that.

This warning is not supposed to appear as we are using useLayoutEffect only when the window is undefined, and we also tested it in Next.js and such a warning was not appearing.

Therefore, we will need to investigate this bug further. In the meantime, can you please tell us if the Grid is also showing this warning in Astro.js?

In addition, we updated and moved all the sample application to the public repo, you can view them here - https://github.com/telerik/kendo-react/tree/master/examples

**Comment by WissamProgress** [comment] 2024-02-01 13:47
The warning was not related to the new ID generation but related to the usage of useLayoutEffect in multiple places in the components. Therefore, we replaced them such that this hook is used only when `window !== undefined` and the warning does not show anymore neither in the Express.js application (kendo-react-ssr) nor Astro.js.

This bug if fixed in the latest dev version and will be available in the upcoming official release:

- https://www.npmjs.com/package/@progress/kendo-react-grid/v/7.1.1-develop.1

**Closed by WissamProgress** 2024-02-01 13:47 UTC
Labels: Bug, SEV: Medium, KendoReact
