### ISSUE TITLE
The .k-header class does not set position to relative, this breaks resizing

### ISSUE THREAD

**Issue by AdamLeBlanc** [telerik/kendo-react#55] opened 2018-08-02 14:52 UTC
When you create a Grid in React, the table headers with the class .k-header do not get their position set to relative. This breaks resizing as the resizing spans end up being pushed to the far right of the grid.

## I'm submitting a...

Support Request

* Regression report 

## Current behavior

If you create the a grid and make components re sizable, the re sizable components are all bunched up in the far right corner of the grid.

## Expected behavior

The .k-header class sets the position to relative and the resizing spans are in the correct location

## Minimal reproduction of the problem with instructions

Use any grid example with the version 1.1.0 of the grid

## What is the motivation or use case for changing the behavior?

So that adding resizing works correctly without having to manually patch.

## Environment

Package versions:

```
+-- @progress/kendo-data-query@1.4.0
+-- @progress/kendo-drawing@1.5.7
+-- @progress/kendo-react-dateinputs@1.1.0
+-- @progress/kendo-react-dropdowns@1.1.0
+-- @progress/kendo-react-grid@1.1.0
+-- @progress/kendo-react-inputs@1.1.0
+-- @progress/kendo-react-intl@1.1.0
+-- @progress/kendo-react-pdf@1.1.0
+-- cldr-data@32.0.1
+-- jest@23.4.2
+-- parcel-bundler@1.9.7
+-- react@16.4.2
`-- react-dom@16.4.2
```

Browser:

- Chrome (desktop) version 68

System:
- Node version: 10.8.0  
- Platform:  Windows

**Comment by Xizario** [comment] 2018-08-03 05:52
@AdamLeBlanc , I would ask you to give some more information about the reproduction instructions. Our [official demos](https://www.telerik.com/kendo-react-ui/components/grid/columns/resizing) are currently using `v1.1.0` and I don't see the issue.
The [demos in develop version](https://www.telerik.com/kendo-react-ui-develop/components/grid/columns/resizing/) of the the are using `v1.2.0-dev.201808020543` And it appears to work as well.

By saying "resizable components", could you name any specific component that you are placing inside the grid? Or you are referring to the draggable resizing handlers of the columns?

Additionally please include the theme and it's version used. I just tested with latest [kendo-theme-material](https://cdn.jsdelivr.net/npm/@progress/kendo-theme-material@dev/dist/all.css) and [kendo-theme-default](https://cdn.jsdelivr.net/npm/@progress/kendo-theme-default@dev/dist/all.css), and not seeing any issue.

**Comment by Xizario** [comment] 2018-10-19 10:14
Closed, because instructions are not clear enough. We will reopen it if there is new info and still happens in v2.3.0 or later

**Comment by feonit** [comment] 2018-12-06 11:59
Hello. He means that with the default scheme turned off, it is expected that the resize will work, I did it too, because I don’t want to customize default styles either. Therefore, we have to add to the `k-header` class `position: relative`. It still happen for v "2.4.0"

**Comment by silviyaboteva** [comment] 2019-10-07 15:53
Tested with the latest [kendo-theme-material](https://cdn.jsdelivr.net/npm/@progress/kendo-theme-material@latest/dist/all.css), [kendo-theme-default](https://cdn.jsdelivr.net/npm/@progress/kendo-theme-default@latest/dist/all.css) and [kendo-theme-bootstrap](https://cdn.jsdelivr.net/npm/@progress/kendo-theme-bootstrap@latest/dist/all.css). `k-header` class has `position: relative` rule that works as expected. Closing this one.

**Closed by silviyaboteva** 2019-10-07 15:53 UTC
Labels: pkg:grid
