### ISSUE TITLE
Controlled state of the `PanelBar`

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#944] opened 2021-05-21 07:50 UTC
The PanelBar should have a controlled state.
It should have the ability to keep one of the items expanded (not to be collapsed when the header is toggled).

Requested under ticket: 1520591.

**Comment by simonssspirit** [comment] 2021-06-25 05:56
This is a duplicate of https://github.com/telerik/kendo-react/issues/583

**Closed by simonssspirit** 2021-06-25 05:56 UTC
Labels: enhancement, pkg:layout
