### ISSUE TITLE
Grid No Data Label Styling Incorrect

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#278] opened 2019-06-25 00:11 UTC
## I'm submitting a...
* Bug report

## Current behavior
When no data label is displayed, it's all squished into the 1st column.

## Expected behavior
Data label should display in a readable way.

## Minimal reproduction of the problem with instructions
Reproducable on demo site
https://www.telerik.com/kendo-react-ui/components/grid/filtering/

1. Type a filter that would result in the no data label being shown.
![image](https://user-images.githubusercontent.com/12272970/60059773-04b7fd00-972d-11e9-9706-3b787c1344a1.png)

## What is the motivation or use case for changing the behavior?
We have dozens of grids on our site, including filtering options. It's a common case that the users would see this issue.

Browser:
- Chrome (desktop) version 75.0.3770.100 (Official Build) (64-bit)

**Comment by Xizario** [comment] 2019-06-25 06:39
It is bug in the themes:
https://github.com/telerik/kendo-themes/issues/781

For example if you use the default theme. It works in `3.6.1` and it is broken in `3.7.0` and will be fixed in `3.8.0`. You can safely use `3.6.1`

**Comment by simonssspirit** [comment] 2019-07-11 14:01
@GeoMarkou The new versions of the themes with the fix are already available and the issue is not reproducible:

![image](https://user-images.githubusercontent.com/11087921/61057255-91390f80-a3fd-11e9-9eba-bf032b01e665.png)

**Closed by simonssspirit** 2019-07-11 14:01 UTC
