### ISSUE TITLE
When clicking on messages at the tops on the Chat, sometime to Chat scrolls to the bottom.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#496] opened 2020-02-26 08:42 UTC
When clicking on messages at the tops on the Chat, sometimes to Chat scrolls to the bottom.

This can be observed in this demo:

https://stackblitz.com/edit/react-hsfgo7?file=app/main.jsx

This can be observed more consistently by clicking outside of the Chat and then the on top messages, do this a couple of times to reproduce it.

**Comment by kspeyanski** [comment] 2020-04-23 07:53
The issue is now resolved in the `dev` version of the `@progress/kendo-react-conversational-ui`:
https://stackblitz.com/edit/react-hsfgo7-8dbzbb

For more information about Obtaining Development Builds please refer to [this](https://www.telerik.com/kendo-react-ui-develop/components/installation/development-builds/) article

**Closed by kspeyanski** 2020-04-23 07:53 UTC
Labels: bug, pkg:conversational-ui
