### ISSUE TITLE
[BUG][DropDownButton] Popup automatically closing after opening it

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1925] opened 2024-01-25 14:46 UTC
**I'm submitting a...**

* Bug report

**Describe the bug**

When having multiple DropDownButtons, when opening one of them then trying to open another one, the Popup opens then closes immediately.

**To Reproduce**

Can be reproduced in this demo - https://www.telerik.com/kendo-react-ui/components/buttons/dropdownbutton/
1. Open any of the components
2. Trying opening another one

**Expected behavior**
The DropDownButton should remain opened.

Ticket ID: 1638541

**Comment by zdravkov** [comment] 2024-02-14 06:59
The issue is fixed in the dev channel on **KendoReact** @progress/kendo-react-buttons package. It will be included in our next official release: https://stackblitz.com/edit/react-sex7yz-878836?file=package.json

**Closed by zdravkov** 2024-02-14 06:59 UTC
Labels: Bug, pkg:Dropdowns, SEV: Medium, KendoReact, Regression
