### ISSUE TITLE
Incorrect styles for Selected and Locked cells

### ISSUE THREAD

**Issue by xarety** [telerik/kendo-react#372] opened 2019-10-31 21:33 UTC
## I'm submitting a...
* Regression report

## Current behavior
Other grid contents shine through locked and selected cells.

## Expected behavior
Locked column obscure other content in the grid

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/selected-locked-column?file=app/main.jsx
1. Select a row
2. Scroll to the right

![image](https://user-images.githubusercontent.com/17852627/67987310-1a3eb580-fc3e-11e9-9749-04dfc00c06e8.png)

**Comment by xarety** [comment] 2019-11-01 11:00
Also, locked cells haven't row hover color.

**Comment by xarety** [comment] 2019-11-01 11:05
@silviyaboteva, or is it intentional?

**Comment by silviyaboteva** [comment] 2019-11-01 11:34
Hi @xarety, 

Indeed, we reproduce both issues and they will be fixed with the next version of themes.
- The first it is due to the fact that selected rows have background color with opacity. Currently, the workaround would be to add the following css rules:

```css
.k-master-row.k-state-selected .k-grid-content-sticky {
	background-color: #ffd8d5;
}

.k-master-row.k-alt.k-state-selected .k-grid-content-sticky {
	background-color: #f8d1ce;
}
```

- The second one (with hover effect) could be fixed applying the following rule:
```css
.k-master-row:hover .k-grid-content-sticky {
	color: #656565;
  background-color: #ededed;
}
```

Demo: https://stackblitz.com/edit/selected-locked-column-8mz7rh?file=index.html 

Thank you for bringing this to our attention!

**Comment by xarety** [comment] 2019-11-01 11:49
You're welcome! A bit wrong hover color for Selected Locked cell.
<img width="278" alt="Capture" src="https://user-images.githubusercontent.com/17852627/68022926-c8864180-fcb6-11e9-836a-8578dd77ba42.PNG">

**Comment by silviyaboteva** [comment] 2019-11-01 11:55
Correct color: 
```
.k-master-row.k-state-selected:hover .k-grid-content-sticky {
	color: #656565;
	background-color: #f2cbc8;
}
```

**Comment by nstoychev** [comment] 2019-11-26 12:50
Fixed. Here is the updated example - https://stackblitz.com/edit/selected-locked-column-ylt8sx.

**Closed by nstoychev** 2019-11-26 12:50 UTC
Labels: bug, pkg:grid
