### ISSUE TITLE
Column Virtualization does not work with locked columns

### ISSUE THREAD

**Issue by fabio-b** [telerik/kendo-react#217] opened 2019-03-18 18:53 UTC
## I'm submitting a...

* Bug report 

## Current behavior

When Column Virtualization is on and you lock a column, it removes the corresponding data cell without removing the column header from view.

## Expected behavior

When column virtualization is on and you lock a column, it keeps both the column header and the data cell associated but removes surrounding columns when out of view.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/react-xumkef?file=app/main.js
Enable Column Virtualization with the required column and grid widths. Apply lock to 1 column. Scroll until it's out of view (reach Field-10). Notice the data cell disappears but the column header remains.

## What is the motivation or use case for changing the behavior?

When column virtualization is on, it should cleanup the inactive columns from the DOM but when a column is locked it should keep data otherwise the grid looks broken with the missing respective data cells.

## Environment

Browser:

- Chrome (desktop) version 74

System:
- Platform:  Mac

**Comment by fabio-b** [comment] 2019-03-25 16:04
I found another use case where column virtualization does not work with custom cell component.
https://stackblitz.com/edit/react-lthexj?file=app%2Fmain.jsx

Let me know if I should open a new issue for this.

**Comment by Xizario** [comment] 2019-05-22 06:29
@fabio-b , the locked with combination with virtual will be fixed in dev soon.

The second case is caused by missing colspan on the cells. You can change the custom rendering from:
`<td style={props.style}>{props.dataItem[props.field]}</td>`
to:
`<td colSpan={props.colSpan} style={props.style}>{props.dataItem[props.field]}</td>`
And it will start to work

**Comment by fabio-b** [comment] 2019-05-22 15:45
Thanks that worked. Are there any estimates for when that release will be done so we can schedule the fix on our side?

**Comment by Xizario** [comment] 2019-05-30 11:45
You can download 3.0.0 or 3.1.0, it is working okay now. If you click the refresh dependencies in the Stackblitz example it works as well.

**Closed by Xizario** 2019-05-30 11:45 UTC
Labels: bug, pkg:grid
