### ISSUE TITLE
[DropDowns] Combobox/MultiSelect with virtualization display empty rows when last item is selected and then opens again

### ISSUE THREAD

**Issue by iadnonov** [telerik/kendo-react#1450] opened 2022-11-15 09:25 UTC
When having a Combobox with virtual scroll enabled, display empty rows when last item is selected and then Combobox opens again.

Ticket ID: 1586664

This can be reproduced here:
https://stackblitz.com/run/?file=app%2Fmain.jsx

## Steps to reproduce
1. Open combobox
2. Scroll to end of the item list
3. Select last item 4999
4. Open combobox again

## Current behaviour
List is opening without any items in it

## Expected behaviour
List is opening with list of items

**Comment by kdikov82** [comment] 2022-12-17 12:34
The same issue is reproduced without selection and only scrolling to the last item, closing the popup and opening it again:
[https://stackblitz.com/edit/react-ny5ufm?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-ny5ufm?file=app%2Fmain.jsx)

The problem is also replicated with the MultiSelect:
[https://stackblitz.com/edit/react-twrp63?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-twrp63?file=app%2Fmain.jsx)

**Comment by kdikov82** [comment] 2022-12-17 12:36
Public item for the MultiSelect: https://feedback.telerik.com/kendo-react-ui/1590786-multiselect-with-virtualization-shows-blank-popup-when-scrolled-to-the-bottom-and-reopened

**Comment by WissamProgress** [comment] 2023-09-14 07:26
Reported in Ticket ID: 1623500

**Comment by elena-gancheva** [comment] 2024-01-25 07:57
related to [#2446](https://github.com/telerik/kendo-react-private/issues/2446)

**Comment by filipKovachev** [comment] 2024-02-09 08:25
Reproducible for the MultiColumnComboBox as well https://stackblitz.com/edit/react-s5d5pk?file=app%2Fmain.tsx

Reported in Ticket 1640409

**Comment by elena-gancheva** [comment] 2024-05-08 14:26
The fix is available in the latest `dev` version of the package and will be available in an official release version on 15th May

**Closed by elena-gancheva** 2024-05-08 14:26 UTC
Labels: Bug, pkg:Dropdowns, SEV: Blocking, KendoReact
