### ISSUE TITLE
Treelist with virtualization fires error when navigating to the last item

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1618] opened 2023-06-27 12:54 UTC
This issue appears when virtualization is enabled, navigatable is set to true, and the number of items is 23 or above. When navigating quickly by holding the arrow down button to the last item, a `Cannot read properties of undefined (reading '0')` TypeError is thrown.

Example: [https://stackblitz.com/edit/react-wqyrjs?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-wqyrjs?file=app%2Fmain.jsx)
Video: [https://somup.com/c01tldz13H](https://somup.com/c01tldz13H)

Ticket ID: 1614092

**Comment by zdravkov** [comment] 2024-07-11 04:22
The issue is fixed in the latest 'dev' version of KendoReact and will be added to the next official release, too - https://stackblitz.com/edit/react-wqyrjs-bqd89j?file=package.json

**Closed by zdravkov** 2024-07-11 04:22 UTC
Labels: Bug, pkg:Treelist, SEV: Critical
