### ISSUE TITLE
Tooltip to append and listen mouse events on custom element

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#855] opened 2021-02-11 12:12 UTC
Currently the Tooltip uses document.body to render and listen mouse events. If there is no document, it simply does not render. This should be configurable. Similar to the appendTo of other components. 

Use Case: 
1) When someone renders the popup using portal inside an iframe.
2) When using shadow DOM.
3) When using 2 or more instances of react.
4) when the `document` var overridden by any custom JS that runs in the global scope. (third party related compatability)

Optionally: add provider for global settings (we can reuse the general Provider that will be shipped for icons, styles, etc.)

**Comment by vladimirivanoviliev** [comment] 2021-06-15 13:22
Seems that the issue is related to that the `top` and `left` of element inside iframe is different than top and left of whole page where the tooltip is rendered (appended).

**Comment by vladimirivanoviliev** [comment] 2021-06-15 13:27
Other issues reported:
- There is no boundary detection which prevents tooltip to be shown on some elements:
![image](https://user-images.githubusercontent.com/2195951/122060740-857ad280-cdf6-11eb-853b-fdc13c2c8583.png)

- Title is not refreshed

**Comment by vladimirivanoviliev** [comment] 2021-08-04 14:23
Fixed in `4.8.0`.

**Closed by vladimirivanoviliev** 2021-08-04 14:23 UTC
Labels: enhancement, pkg:tooltip
