### ISSUE TITLE
`fontSize`, `fontWeight` and `margin` props of the Typography do not apply any styles

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#1580] opened 2023-05-24 15:30 UTC
Ticket ID: 1609863

Changing the values of the `fontSize`, `fontWeight` and `margin` props do not change the styling of the Typography content.

The problem can be reproduced in the demos available here:
https://www.telerik.com/kendo-react-ui/components/utils/typography/appearance/

**Comment by kikostadinov** [comment] 2023-05-25 10:49
This is caused by the styles of utility classes k-m-*, k-font-weight-* and k-fs-* being overwritten by the styles of element classes.

A workaround would be setting importance to the utility class, e.g. `!k-font-weight-*`.

Issue in the themes: https://github.com/telerik/kendo-themes/issues/4502

**Comment by silviyaboteva** [comment] 2024-05-17 11:09
The issue is related to Kendo Themes and it starts from `v6.2.0` where the utility classes are imported prior to the components' styles. Detaching all of the utilities from the themes will be the solution.

Closing this, as there is an open issue in themes: https://github.com/telerik/kendo-themes/issues/4502

**Closed by silviyaboteva** 2024-05-17 11:09 UTC
Labels: Bug, pkg:Common-utilities
