### ISSUE TITLE
Grid with enabled virtual scrolling (rows and columns) cause all rows to disappear randomly while scrolling

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1270] opened 2022-04-01 15:54 UTC
Example replicating the issue:

- [https://stackblitz.com/edit/react-u6s5vf-jhz8tv?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-u6s5vf-jhz8tv?file=app%2Fmain.jsx)

Steps to reproduce:
1) Open the example in new window
2) Scroll to the middle of the Grid`s scrollbar fast and let go of the scroll. Almost every time (but not always), the rows will not be visible. 
3) Scrolling up or down with the mouse wheel will show the rows

Another issue is that some of the top rows might also not be visible when **scrolling up** (randomly).
The scrolling is extremely slow even with reduced number of columns.

**Comment by InaGlushkova** [comment] 2022-04-22 06:50
A related issue was reported under https://github.com/telerik/kendo-react/issues/1278

**Comment by InaGlushkova** [comment] 2022-04-22 07:03
A related issue was reported again under ticket 1562443.

_**Additional information about the issue:**_

When a filter that does not change the data count is applied grid shows an empty state until you scroll.
Steps to reproduce:
1. Go to this example: https://stackblitz.com/edit/react-1u4myn?file=app/main.jsx
2. Scroll about 50 items.
3. Change the filter of the Discontinued column to "Check all"

When you reset the table skip value 0 (or any other value) grid shows an empty state until you scroll. 
1. Go to this example: https://stackblitz.com/edit/react-1u4myn?file=app/main.jsx
2. Scroll about 50 items.
3. Click the Set Skip 0 button

When you set the initial skip to some value grid shows correct data but when you start scrolling it sets the skip to 0.
1. Go to this example: https://stackblitz.com/edit/react-1u4myn?file=app/main.jsx
2. Change skip in line 18 to 50
3. Start scrolling it will reset skip to 0

**Comment by InaGlushkova** [comment] 2022-05-01 19:08
Reported again under ticket 1563407.

**Comment by InaGlushkova** [comment] 2022-05-24 09:24
Reported again under: 1566225

**Comment by filipKovachev** [comment] 2022-09-01 08:28
Reported again in 1578093

**Comment by nstoychev** [comment] 2023-02-03 11:03
It looks resolved with version 5.10.1.

Here is the updated example: https://stackblitz.com/edit/react-u6s5vf-p1w9vp?file=app%2Fmain.jsx

**Comment by da1z** [comment] 2023-02-07 22:25
> When a filter that does not change the data count is applied grid shows an empty state until you scroll.
> 
> 1. Go to this example: https://stackblitz.com/edit/react-1u4myn?file=app/main.jsx
> 2. Scroll about 50 items.
> 3. Change the filter of the Discontinued column to "Check all"

@nstoychev these are still reproducible. first one for sure

**Comment by nstoychev** [comment] 2023-02-08 13:49
@da1z This case will not be covered in this issue. I logged it here: https://github.com/telerik/kendo-react/issues/1488.

**Comment by nstoychev** [comment] 2023-02-08 15:47
Example with React 18 createRoot API using version 5.11.1-dev.202302071533: https://stackblitz.com/edit/react-u6s5vf-15yxcx?file=app%2Fmain.jsx

**Comment by da1z** [comment] 2023-02-22 00:27
> 3\. Discontinued

thanks! with settings skip to 0 I was trying to scroll grid to top, with your example it works!

But as for this:

> When a filter that does not change the data count is applied grid shows an empty state until you scroll.
> 
> Go to this example: https://stackblitz.com/edit/react-1u4myn?file=app/main.jsx
> Scroll about 50 items.
> Change the filter of the Discontinued column to "Check all"

The issue is different. When you change filters so rows count does not change, as for example selecting all options in filter, the grid becomes empty until scroll

**Comment by nstoychev** [comment] 2023-02-22 08:05
@da1z

> When a filter that does not change the data count is applied grid shows an empty state until you scroll.

This is resolved in [5.11.1-dev.202302131506](https://github.com/telerik/kendo-react/issues/1488#issuecomment-1429270302) - Changelog is [here](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#d0c1f968-1376-53fe-9279-a7a4743391c7).

Example: https://stackblitz.com/edit/react-1u4myn-yegn7d?file=app%2Fmain.jsx.

**Closed** 2023-03-16 10:27 UTC
Labels: bug, pkg:grid, Priority 4, SEV: High
