### ISSUE TITLE
[Bug][DropDownButton] Closed automatically in controlled mode

### ISSUE THREAD

**Issue by zoran995** [telerik/kendo-react#1871] opened 2024-01-22 13:10 UTC
## I'm submitting a...
* Regression report 

## Steps to reproduce
1. Open https://stackblitz.com/edit/react-axf6pe?file=app%2Fmain.tsx
2. Click on the `User settings` button
3. Click on some dropdown item, and observe dropdown being closed

## Current behaviour
When having a DropDownButton in controlled mode with the `opened` prop set to `true` it will close automatically although the prop value is still `true`

## Expected behaviour
While `opened` is set to `true` the dropdown should remain open, no matter where user clicked and change visibility only on prop change. The same behaviour can be seen on DropDownList. This behaviour was up until 5.18.0, most probably before #1690 changes - https://stackblitz.com/edit/react-axf6pe-jzne3y?file=app%2Fmain.tsx,package.json (attaching a demo on v5.13.1 as that is the last version that is mentioned working in #1690)

**Comment by zdravkov** [comment] 2024-01-24 12:49
Hey @zoran995 ,

It looks like a bug indeed. Thank you for reporting it and please excuse us for the inconvenience caused. We will do our best to fix it as soon as possible. 

If you have any other questions, please don't hesitate to submit a ticket in [our support system](https://www.telerik.com/account/support-center) where we do our best to answer all possible questions regarding KendoReact suite.

Greetings,
Plamen

**Comment by vveesseelliinnaa** [comment] 2024-01-29 13:35
Reported also in Ticket ID: 1638638

**Comment by zdravkov** [comment] 2024-02-14 07:01
The issue is fixed in the dev channel on **KendoReact @progress/kendo-react-buttons** package. It will be included in our next official release: https://stackblitz.com/edit/react-axf6pe-q3weut?file=package.json,app%2Fmain.tsx

**Closed by zdravkov** 2024-02-14 07:01 UTC
Labels: Bug, pkg:Buttons, SEV: High, KendoReact, Regression

**Comment by zoran995** [comment] 2024-02-14 10:28
@zdravkov Thanks for fixing it, I just quickly checked the provided stackblitz, and the reported bug is resolved, but there is just one slightly odd/inconsistent behaviour. I can open a new issue if needed

Steps:
- Open the stackblitz
- Click on the dropdown button
- click outside the dropdown - observe it is closed although the prop opened is still true
- open the dropdown again
- click outside the dropdown - observe it stays open

Here is also a video

https://github.com/telerik/kendo-react/assets/19208948/66330809-ddbe-4d0e-bc1e-cb1a9965ccb1
