### ISSUE TITLE
Changing the value of the Slider/RangeSlider scrolls the whole page

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1500] opened 2023-02-27 11:17 UTC
This issue can only be reproduced **locally** - [slider-test.zip](https://github.com/telerik/kendo-react/files/10839013/slider-test.zip)

When the Slider or RangeSlider component is dragged to change its value, it scrolls the whole page.
[https://somup.com/c0ntlmyI6O](https://somup.com/c0ntlmyI6O)

Currently, you can workaround this issue by removing `<!DOCTYPE html>` from `index.html`

Related to Ticket ID: 1598791

**Comment by kdikov82** [comment] 2023-02-28 06:40
I was able to reproduce the problem on stackblitz:
https://stackblitz.com/edit/react-hsab6q?file=app%2Fmain.jsx

One thing that I have discovered is that the issue is not observed if the DIV above the slider is with smaller height (1000 instead of 2000px for example):
https://stackblitz.com/edit/react-hsab6q-njhmb5?file=app%2Fmain.jsx

**Comment by JDoro** [comment] 2024-06-19 21:17
Has there been any progress made on this? We are seeing this as well.

**Comment by ksoich** [comment] 2024-06-19 22:30
It seems this issue is related to the `autoScroll` prop of `Draggable`. 

`autoScroll` is not explicitly defined and defaults to `true`.

Explicitly setting `autoScroll` based on the orientation of the slider - the jumping behavior does not occur.
![image](https://github.com/telerik/kendo-react/assets/99049491/e5d2f8b2-7f6a-4843-80b5-e3e24f877709)

**Comment by iadnonov** [comment] 2024-06-20 11:58
Hi, @ksoich, Thank you for your suggestion. Our team will consider it as they work on resolving the issue.

**Comment by zdravkov** [comment] 2024-07-15 06:30
The issue is fixed in the 'dev' npm KendoREact package and will be available in the next official release. - https://stackblitz.com/edit/react-hsab6q-hwzf2w?file=app%2Fmain.jsx,package.json
In general we don't expect autoscroll in any case while we interact with the slider.

**Closed by zdravkov** 2024-07-15 06:30 UTC
Labels: Bug, pkg:Inputs, SEV: High, KendoReact, triaged
