### ISSUE TITLE
[Filter] Misleading title in the remove buttons

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1702] opened 2023-09-21 06:03 UTC
All "Remove" buttons within the Filter component are currently showing "Close" title.

The expected behavior:
- The title should be replaced with "Remove", since it better represents the action

We should also investigate if we can remove the "Remove" button for the initial CompositeFilter if there are no filter expressions and when it is first element in the tree. Currently, if there are no filter expressions, the initial element will still render a remove button, which will remove it under the hood, but will replace it with a new one, so it seems like the remove button is not doing anything:

- https://stackblitz.com/edit/react-jgm8dv?file=app%2Fmain.jsx

![filter_image_2](https://github.com/telerik/kendo-react/assets/11787141/ea49afea-ab41-4e5d-87dc-0c08b43604ab)
![filter_image_1](https://github.com/telerik/kendo-react/assets/11787141/f20e3c78-1487-4210-91ee-dfa4e53e5e36)

**Comment by zdravkov** [comment] 2024-02-15 15:47
The issue is fixed in the dev channel on KendoReact. It will be included in our next official release - https://stackblitz.com/edit/react-jgm8dv-yjoaoh?file=package.json

**Closed by zdravkov** 2024-02-15 15:47 UTC
Labels: Bug, pkg:DataTools
