### ISSUE TITLE
Scheduler - navigation arrows don't fire handleDateChange

### ISSUE THREAD

**Issue by dyabol** [telerik/kendo-react#476] opened 2020-02-13 10:23 UTC
If i use **date** and **onDateChange** to control current month, all works well until click to arrows in top.

"@progress/kendo-react-scheduler": "3.10.1"

The problem can be caused also in the documentation:

[https://www.telerik.com/kendo-react-ui/components/scheduler/date-selection/#toc-controlled-mode](url)

**Comment by kspeyanski** [comment] 2020-02-13 12:00
Hello @dmihaylo ,

Thank you for reporting this issue. After investigating, it seems that the demo is setup incorrectly.
In order for the Scheduler to detect the current active view and it's range step, the [`defaultView`](https://www.telerik.com/kendo-react-ui/components/scheduler/api/SchedulerProps/#toc-defaultview) or [`view`](https://www.telerik.com/kendo-react-ui/components/scheduler/api/SchedulerProps/#toc-view) properties must be set.

We will be rolling a hot-fix for the Scheduler to be able to auto-detect if only a single view is specified, thus removing the need of specifying the `defaultView`/`view` properties expllicitly.

I'll be writing back in this issue once the hot-fix has been published, in the mean time, i've added the necessary properties in the following stackblitz example:
https://stackblitz.com/edit/react-wnhesf

Please let me know if you need further assistance.

**Comment by dyabol** [comment] 2020-03-20 12:35
> Hello @dmihaylo ,
> 
> Thank you for reporting this issue. After investigating, it seems that the demo is setup incorrectly.
> In order for the Scheduler to detect the current active view and it's range step, the [`defaultView`](https://www.telerik.com/kendo-react-ui/components/scheduler/api/SchedulerProps/#toc-defaultview) or [`view`](https://www.telerik.com/kendo-react-ui/components/scheduler/api/SchedulerProps/#toc-view) properties must be set.
> 
> We will be rolling a hot-fix for the Scheduler to be able to auto-detect if only a single view is specified, thus removing the need of specifying the `defaultView`/`view` properties expllicitly.
> 
> I'll be writing back in this issue once the hot-fix has been published, in the mean time, i've added the necessary properties in the following stackblitz example:
> https://stackblitz.com/edit/react-wnhesf
> 
> Please let me know if you need further assistance.

It works! But if I set defaultView = "month", a select view is displayed with one item.

**Comment by kspeyanski** [comment] 2020-04-06 12:47
Hello @dyabol,

We have published a `dev` version of the `@progress/kendo-react-scheduler` package, where the issue is resolved.
The correct navigation can be observed in the following stackblitz demo:
https://stackblitz.com/edit/react-wnhesf-rylug3?file=app/main.jsx

For more information about obtaining `dev` build, please refer to the following article:
https://www.telerik.com/kendo-react-ui/components/installation/development-builds/

**Closed by kspeyanski** 2020-04-06 12:47 UTC
Labels: bug
