### ISSUE TITLE
Version upgrade from kendo react 7.3.0 to 8.0.0 latest stable.

### ISSUE THREAD

**Issue by mdnghimire** [telerik/kendo-react#2278] opened 2024-05-29 15:50 UTC
I've successfully upgrade and install packages but while npm run dev in latest @progress/kendo-react-all": "^8.0.0 I got error like this as show in the below

⨯ ./node_modules/@progress/kendo-react-all/index.mjs
The requested module '@progress/kendo-react-charts' contains conflicting star exports for the name 'ZoomEndEvent' with the previous requested module '@progress/kendo-react-map'

I wanna upgrade my current 7.3.0 into lastest stable version but I'm getting this error ??

**Comment by WissamProgress** [comment] 2024-05-30 08:10
Hi @mdnghimire 

In [v7.4.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#v7.4.0), in the kendo-react-all package, the ZoomEndEvent has been renamed to ChartZoomEndEvent for the event of the kendo-react-charts package, and ZoomEndEvent can be imported for the event exported from the kendo-react-map package. We did this renaming after refactoring the all package and exporting all types, functions, and components that exist for the KendoReact packages. Some had identically named exported, so we renamed them (only in the kendo-react-all package).

We will document all the renamed exports soon. Apologies for that.

Now for the faced issue, can you please provide me with some additional information? For example, are you importing both the kendo-react-all and the kendo-react-charts package together, or only installing and importing the kendo-react-all package? It would also be very helpful if you send me a code example.

**Comment by mdnghimire** [comment] 2024-06-01 16:00
@WissamProgress I have installed packages like this

"dependencies": {
    "@auth/prisma-adapter": "^1.4.0",
    "@prisma/client": "^5.10.2",
    "@progress/kendo-data-query": "^1.7.0",
    "@progress/kendo-react-all": "^8.0.0",
    "@progress/kendo-react-common": "^8.0.0",
    "@progress/kendo-react-spreadsheet": "^8.0.0",
    "@progress/kendo-react-treelist": "^8.0.0",
    "@progress/kendo-svg-icons": "^3.0.0",
    "@progress/kendo-theme-bootstrap": "^7.2.1",
    "@storybook/addon-essentials": "^7.6.7",
    "@storybook/addon-interactions": "^7.6.7",
    "@storybook/addon-links": "^7.6.7",
    "@storybook/addon-onboarding": "^1.0.10",
    "@storybook/blocks": "^7.6.7",
    "@storybook/cli": "^7.6.17",
    "@storybook/nextjs": "^7.6.7",
    "@storybook/react": "^7.6.8",
    "@storybook/test": "^7.6.7",
    "@storybook/theming": "^7.6.8",
    "@tanstack/react-query": "^5.28.8",
    "@tisoap/react-flow-smart-edge": "^3.0.0",
    "@zenstackhq/runtime": "^1.11.1",
    "@zenstackhq/server": "^1.11.1",
    "@zenstackhq/tanstack-query": "^1.11.1",
    "axios": "^1.6.3",
    "babel-plugin-module-resolver": "^5.0.0",
    "bcrypt": "^5.1.1",
    "date-fns": "^3.3.1",
    "dompurify": "^3.0.8",
    "esbuild": "^0.20.1",
    "next": "14.0.4",
    "next-auth": "^4.24.5",
    "next-themes": "^0.2.1",
    "playwright": "^1.41.1",
    "react": "^18",
    "react-dom": "^18",
    "react-icons": "^5.0.0",
    "react-outside-click-handler": "^1.3.0",
    "react-select": "^5.8.0",
    "react-toastify": "^10.0.4",
    "reactflow": "^11.11.1",
    "storybook": "^7.6.7",
    "storybook-dark-mode": "^3.0.3",
    "use-debounce": "^10.0.0",
    "xml-js": "^1.6.11",
    "zod": "^3.22.4",
    "zod-validation-error": "^2.1.0"
  },  

I wanna upgrade from 7.3.0 to latest 8.0.0
as I have previous and upgraded version as show in this screenshot

![Screenshot (199)](https://github.com/telerik/kendo-react/assets/156049432/f0842570-2c8b-4fc7-8459-c500e62211b5)

packages installed successfully with npm i
but when runing project npm run dev I got error like this as shown below

I do have imported kendo-react-all but I haven't imported  kendo-react-charts package.

![Screenshot 2024-06-01 213852](https://github.com/telerik/kendo-react/assets/156049432/8fedc484-8f6b-48fc-b095-d317d6b7d637)

**Comment by WissamProgress** [comment] 2024-06-03 12:21
Hi @mdnghimire 

This is indeed a bug, thank you so much for reporting it. We will do our best to fix this as soon as possible.

**Comment by mdnghimire** [comment] 2024-06-03 13:31
> Hi @mdnghimire
> 
> This is indeed a bug, thank you so much for reporting it. We will do our best to fix this as soon as possible.

Thank you for your prompt response. I appreciate your team efforts to fix this issue as soon as possible.

**Comment by WissamProgress** [comment] 2024-06-10 15:01
Fixed in [8.1.0-develop.5](https://www.npmjs.com/package/@progress/kendo-react-all/v/8.1.0-develop.5) and will be available in the upcoming official release.

Here is a test project with this version - [my-app.zip](https://github.com/user-attachments/files/15775232/my-app.zip)

**Closed by WissamProgress** 2024-06-10 15:01 UTC
Labels: Bug, KendoReact, Regression

**Comment by madanghimire-3ptrades** [comment] 2024-06-14 02:12
> Fixed in [8.1.0-develop.5](https://www.npmjs.com/package/@progress/kendo-react-all/v/8.1.0-develop.5) and will be available in the upcoming official release.
> 
> Here is a test project with this version - [my-app.zip](https://github.com/user-attachments/files/15775232/my-app.zip)

Thank you! The issue is now resolved and everything is working fine with version 8.1.0-develop.5 , I look forward to the upcoming official release.
