### ISSUE TITLE
NumeriTextBox is shown as invalid in some cases when changing the value with the spinners.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#495] opened 2020-02-26 08:22 UTC
NumeriTextBox is shown as invalid in some cases when changing the value with the spinners.

This can be observed in this demo:

https://stackblitz.com/edit/react-kqg36e-kmrs9y?file=index.js

Click the up arrow until the value is "0.750%" and notice how the NumericTextBox is shown as invalid.

**Comment by vladimirivanoviliev** [comment] 2020-02-26 15:40
The issue is now fixed on our side and the fix will be released with next dev version, expected to the end of the week. The reason for current behavior was unhandled JS number rounding during increase/decrease actions (producing `0.007500000000000001` instead of `0.0075`).

**Comment by robv8r** [comment] 2020-02-27 13:34
Thank you for the quick fix.  I can no longer reproduce the error using the following `dev` package:

    "@progress/kendo-react-inputs": "^3.12.0-dev.202002270742"

**Closed** 2020-02-27 13:45 UTC
Labels: bug, pkg:inputs
