### ISSUE TITLE
DatePicker Animation does not work when calendar opens upwards

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#257] opened 2019-05-23 12:58 UTC
## I'm submitting a...

* Bug report 

## Current behavior
When the calendar opens upwards it does not animate. It should do the same animation the way it does when opening downwards

Related issue was reported here: https://github.com/telerik/kendo-react/issues/158
However in that issue it is assumed this affects only iOS devices, but it also has an impact on normal desktop devices.

## Expected behavior
Same smooth animation as when opening downwards

## Minimal reproduction of the problem with instructions
See demo site fork here:
https://stackblitz.com/edit/react-epjh28?file=app/main.jsx
Make sure datepicker is at the bottom of screen so it opens upwards

## What is the motivation or use case for changing the behavior?
Smooth user experience

## Environment

Browser:

- Chrome (desktop) version 74

System:
- Platform:   Windows

**Comment by kspeyanski** [comment] 2019-10-07 05:49
Hello @k290 ,

After updating the `@progress/kendo-react-dateinputs` package to version `3.4.1`, the issue is no longer reproducible: https://stackblitz.com/edit/react-epjh28-c3pnng?file=app/main.jsx

I believe the issue was resolved by improving the `focus` logic of the component in version [3.2.1](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#toc-321), which can trigger a layout reflow and break the animation.

Please let me know if you have any problems with the component on your side.

**Closed by kspeyanski** 2019-10-07 05:49 UTC
Labels: bug, pkg:dateinputs, pkg:popup
