### ISSUE TITLE
MultiSelect with virtualization will not scroll past a selected item when scrolling with the mouse wheel.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#738] opened 2020-09-29 09:24 UTC
MultiSelect with virtualization will not scroll past a selected item when scrolling with the mouse wheel.

This can be reproduced in the following demo:

https://www.telerik.com/kendo-react-ui-develop/components/dropdowns/multiselect/virtualization/

Steps:

1) Selected item 50.
2) Open the MultiSelect and scroll up with the mouse wheel.
3) The scrolling will stop when item 50 is at the bottom of the list.

**Comment by nstoychev** [comment] 2020-10-12 07:19
Another case reported in ticket: 1489253.
The MultiSelect scrolls to the last selected item when the app state is changed.

**Comment by kdikov82** [comment] 2023-01-28 14:58
The issue seems to be resolved with the latest version (5.11.0):
[https://stackblitz.com/edit/react-nakmtg?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-nakmtg?file=app%2Fmain.jsx)

**Comment by elena-gancheva** [comment] 2024-05-08 14:26
This issue is no longer reproducible

**Closed by elena-gancheva** 2024-05-08 14:26 UTC
Labels: Bug, pkg:Dropdowns
